[package]
name = "quantforge-export-mql5"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
quantforge-broker.workspace = true
quantforge-core.workspace = true
quantforge-ir.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
include_dir = "0.7.4"

[dev-dependencies]
quantforge-eval.workspace = true
