//+------------------------------------------------------------------+
//| @@EXPERT_NAME@@ EA
//|
//|    Generated by QuantForge SQX-style export for MetaTrader5
//|    Strategy fingerprint: @@STRATEGY_FINGERPRINT@@
//+------------------------------------------------------------------+

#property copyright "QuantForge"
#property link      "https://quantforge.local"
#property strict
#property version   "1.00"
#property description "QuantForge SQX-style Strategy IR export."

#property tester_indicator "SqATR"
#property tester_indicator "SqADX"
#property tester_indicator "SqSupplyDemand"
#property tester_indicator "SqStochastic"
#property tester_indicator "SqROC"
#property tester_indicator "SqHighest"
#property tester_indicator "SqLowest"
#property tester_indicator "SqZScore"
#property tester_indicator "SqATRPercentile"
#property tester_indicator "SqLiquiditySweep"
#property tester_indicator "SqOpeningRange"

#include <Trade/Trade.mqh>

// Runtime helpers are inlined so a lone .mq5 still compiles if the sibling
// sqx_runtime.mqh was not copied into Experts/.
@@SQX_RUNTIME@@

#define QFValid sqValid
#define QFPrice sqPrice
#define QFMA sqMa
#define QFRSI sqRsi
#define QFATR sqSqAtr
#define QFADX sqSqAdx
#define QFPlusDI sqPlusDi
#define QFMinusDI sqMinusDi
#define QFStdDev sqStdDev
#define QFExtreme sqExtreme
#define QFSwingBaseZoneHigh sqSwingBaseZoneHigh
#define QFSwingBaseZoneLow sqSwingBaseZoneLow
#define QFLiquiditySweepScore sqLiquiditySweepScore
#define QFGreater sqGreater
#define QFLess sqLess
#define QFCrossAbove sqCrossAbove
#define QFCrossBelow sqCrossBelow

input string CustomComment="@@EXPERT_NAME@@";
input bool   InpAllowLiveTrading=@@ALLOW_LIVE@@;
input ulong  InpMagic=@@MAGIC@@;
input int    InpDeviationPoints=@@DEVIATION@@;
input double InpMaxSpreadPoints=@@MAX_SPREAD@@;
input double InpEstimatedSlippagePointsPerSide=@@SLIPPAGE@@;
input double InpCommissionPerLotRoundTurn=@@COMMISSION@@;
input int    InpEntryWindowStartHour=@@ENTRY_WINDOW_START@@;
input int    InpEntryWindowEndHour=@@ENTRY_WINDOW_END@@;
input string InpParityPrefix="@@PARITY_PREFIX@@";

CTrade g_trade;
datetime g_last_bar=0;
datetime g_last_exit_bar=0;
int g_loss_streak=0;
int g_decision_bars_seen=0;
int g_entry_day_key=0;
int g_entries_today=0;
int g_deals_file=INVALID_HANDLE;
int g_equity_file=INVALID_HANDLE;
int g_metadata_file=INVALID_HANDLE;
bool g_equity_recorded=false;
double g_last_equity_balance=0.0;
double g_last_equity=0.0;
double g_initial_volume=0.0;
double g_initial_risk=0.0;
double g_peak_favorable=EMPTY_VALUE;
bool g_partial_done[];
bool LongEntrySignal=false;
bool ShortEntrySignal=false;
bool LongExitSignal=false;
bool ShortExitSignal=false;

// Broker specification hash: @@BROKER_FINGERPRINT@@

double QFZScore(const int field,const ENUM_APPLIED_PRICE source,
                const int period,const int shift)
{
   if(field==3 && source==PRICE_CLOSE)
      return sqSqZScore(period,shift);
   const double value=QFPrice(field,shift);
   const double mean=QFMA(MODE_SMA,source,period,shift);
   const double deviation=QFStdDev(source,period,shift);
   if(!QFValid(value) || !QFValid(mean) || !QFValid(deviation) || deviation<=0.0)
      return EMPTY_VALUE;
   return (value-mean)/deviation;
}

double QFPercentile(const int field,const ENUM_SERIESMODE mode,
                    const int period,const int shift)
{
   const double value=QFPrice(field,shift);
   const double low=QFExtreme(mode,field,period,shift,false);
   const double high=QFExtreme(mode,field,period,shift,true);
   if(!QFValid(value) || !QFValid(low) || !QFValid(high) || high<=low)
      return EMPTY_VALUE;
   return (value-low)/(high-low)*100.0;
}

double QFROC(const int field,const int period,const int shift)
{
   if(field==3)
      return sqSqRoc(period,shift);
   const double current=QFPrice(field,shift);
   const double previous=QFPrice(field,shift+period);
   if(!QFValid(current) || !QFValid(previous) || previous==0.0)
      return EMPTY_VALUE;
   return (current/previous-1.0)*100.0;
}

double QFBodyRangeRatio(const int shift)
{
   const double open=QFPrice(0,shift);
   const double high=QFPrice(1,shift);
   const double low=QFPrice(2,shift);
   const double close=QFPrice(3,shift);
   if(!QFValid(open) || !QFValid(high) || !QFValid(low) || !QFValid(close))
      return EMPTY_VALUE;
   const double range=high-low;
   if(range<=0.0)
      return EMPTY_VALUE;
   return MathAbs(close-open)/range;
}

double QFCloseLocationInBar(const int shift)
{
   const double high=QFPrice(1,shift);
   const double low=QFPrice(2,shift);
   const double close=QFPrice(3,shift);
   if(!QFValid(high) || !QFValid(low) || !QFValid(close))
      return EMPTY_VALUE;
   const double range=high-low;
   if(range<=0.0)
      return EMPTY_VALUE;
   return (close-low)/range;
}

double QFAtrPercentile(const int atr_period,const int lookback,const int shift)
{
   if(atr_period<1 || lookback<1 || Bars(_Symbol,_Period)<shift+lookback)
      return EMPTY_VALUE;
   return sqSqAtrPercentile(atr_period,lookback,shift);
}

bool QFSameBrokerDay(const datetime left,const datetime right)
{
   MqlDateTime a,b;
   if(!TimeToStruct(left,a) || !TimeToStruct(right,b))
      return false;
   return a.year==b.year && a.mon==b.mon && a.day==b.day;
}

double QFSessionRangeExtreme(const int start_hour,const int range_bars,const int shift,
                             const bool want_high)
{
   // Mirror quantforge_sqx::session_range_series:
   // 1) first same-day bar with hour >= start_hour is the window start
   // 2) freeze high/low over the next `range_bars` bars (inclusive)
   // 3) carry that frozen extreme for the rest of the day
   if(range_bars<1 || shift<0 || Bars(_Symbol,_Period)<=shift)
      return EMPTY_VALUE;
   const datetime anchor=iTime(_Symbol,_Period,shift);
   if(anchor<=0)
      return EMPTY_VALUE;
   MqlDateTime parts;
   if(!TimeToStruct(anchor,parts))
      return EMPTY_VALUE;

   // Walk oldest→newest on the anchor's broker day to find window start.
   int window_start=-1;
   for(int index=Bars(_Symbol,_Period)-1;index>=shift;index--)
   {
      const datetime bar_time=iTime(_Symbol,_Period,index);
      if(bar_time<=0 || !QFSameBrokerDay(bar_time,anchor))
         continue;
      MqlDateTime bar_parts;
      if(!TimeToStruct(bar_time,bar_parts))
         continue;
      if(bar_parts.hour>=start_hour)
      {
         window_start=index;
         break;
      }
   }
   if(window_start<0)
      return EMPTY_VALUE;

   // Window newest bar index = window_start - (range_bars - 1). Must have formed
   // by `shift` (equal or older than the evaluation bar).
   const int window_end=window_start-(range_bars-1);
   if(window_end<shift)
      return EMPTY_VALUE;

   double extreme=want_high ? -DBL_MAX : DBL_MAX;
   int collected=0;
   for(int index=window_start;index>=window_end;index--)
   {
      const datetime bar_time=iTime(_Symbol,_Period,index);
      if(bar_time<=0 || !QFSameBrokerDay(bar_time,anchor))
         return EMPTY_VALUE;
      MqlDateTime bar_parts;
      if(!TimeToStruct(bar_time,bar_parts) || bar_parts.hour<start_hour)
         return EMPTY_VALUE;
      if(want_high)
         extreme=MathMax(extreme,iHigh(_Symbol,_Period,index));
      else
         extreme=MathMin(extreme,iLow(_Symbol,_Period,index));
      collected++;
   }
   if(collected!=range_bars)
      return EMPTY_VALUE;
   return extreme;
}

double QFSessionRangeHigh(const int start_hour,const int range_bars,const int shift)
{
   return QFSessionRangeExtreme(start_hour,range_bars,shift,true);
}

double QFSessionRangeLow(const int start_hour,const int range_bars,const int shift)
{
   return QFSessionRangeExtreme(start_hour,range_bars,shift,false);
}

double QFAverageRange(const int period,const int shift)
{
   if(period<1 || Bars(_Symbol,_Period)<shift+period)
      return EMPTY_VALUE;
   double sum=0.0;
   for(int index=shift;index<shift+period;index++)
      sum+=iHigh(_Symbol,_Period,index)-iLow(_Symbol,_Period,index);
   return sum/(double)period;
}

double QFContext(const int field,const int shift)
{
   const datetime value=iTime(_Symbol,_Period,shift);
   if(value<=0)
      return EMPTY_VALUE;
   MqlDateTime parts;
   if(!TimeToStruct(value,parts))
      return EMPTY_VALUE;
   return field==0 ? (double)parts.hour : (double)parts.day_of_week;
}

@@QF_EXTENDED_INDICATORS@@

bool QFBetween(const double value,const double lower,const double upper)
{
   return QFValid(value) && QFValid(lower) && QFValid(upper)
          && value>=lower && value<=upper;
}

bool QFLongSignal(const int extra_shift)
{
   return @@LONG_SIGNAL@@;
}

bool QFShortSignal(const int extra_shift)
{
   return @@SHORT_SIGNAL@@;
}

bool QFExitSignal(const int extra_shift)
{
   if(!QFOwnPosition())
      return false;
   const long position_type = PositionGetInteger(POSITION_TYPE);
   if(position_type == POSITION_TYPE_BUY)
      return @@LONG_EXIT_SIGNAL@@;
   if(position_type == POSITION_TYPE_SELL)
      return @@SHORT_EXIT_SIGNAL@@;
   return false;
}

bool QFFilters(const int extra_shift)
{
   return @@FILTERS@@;
}

double QFStopDistance()
{
   return @@STOP_DISTANCE@@;
}

double QFTargetDistance(const double stop_distance)
{
   return @@TARGET_DISTANCE@@;
}

double QFRiskBudget()
{
   return @@RISK_BUDGET@@;
}

int QFVolumeMode()
{
   return @@VOLUME_MODE@@;
}

double QFFixedLots()
{
   return @@FIXED_LOTS@@;
}

double QFMartingaleMultiplier()
{
   return @@MARTINGALE_MULTIPLIER@@;
}

int QFMartingaleMaxSteps()
{
   return @@MARTINGALE_MAX_STEPS@@;
}

double QFMartingaleLots()
{
   const int steps=(int)MathMin(g_loss_streak,QFMartingaleMaxSteps());
   return QFFixedLots()*MathPow(QFMartingaleMultiplier(),steps);
}


int QFAtrRiskPeriod()
{
   return @@ATR_RISK_PERIOD@@;
}

double QFAtrRiskMultiplier()
{
   return @@ATR_RISK_MULTIPLIER@@;
}

double QFAtrRiskMaxLots()
{
   return @@ATR_RISK_MAX_LOTS@@;
}

double QFAtrRiskDistance()
{
   const double atr=QFATR(QFAtrRiskPeriod(),1);
   if(!QFValid(atr) || atr<=0.0)
      return 0.0;
   return atr*QFAtrRiskMultiplier();
}
double QFResolveVolume(const double risk_per_lot)
{
   const int mode=QFVolumeMode();
   if(mode==1)
      return QFFixedLots();
   if(mode==2)
      return QFMartingaleLots();
   if(mode==3)
   {
      const double atr_distance=QFAtrRiskDistance();
      if(atr_distance<=0.0)
         return 0.0;
      const double tick_size=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
      const double tick_value=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
      if(tick_size<=0.0 || tick_value<=0.0)
         return 0.0;
      const double atr_risk_per_lot=atr_distance/tick_size*tick_value;
      if(atr_risk_per_lot<=0.0)
         return 0.0;
      double lots=QFRiskBudget()/atr_risk_per_lot;
      const double max_lots=QFAtrRiskMaxLots();
      if(max_lots>0.0)
         lots=MathMin(lots,max_lots);
      return lots;
   }
   if(risk_per_lot<=0.0)
      return 0.0;
   return QFRiskBudget()/risk_per_lot;
}

int QFEntryOrderKind()
{
   return @@ENTRY_ORDER_KIND@@;
}

double QFEntryDistance()
{
   return @@ENTRY_DISTANCE@@;
}

double QFEntryLimitOffset()
{
   return @@ENTRY_LIMIT_OFFSET@@;
}

int QFEntryExpiryBars()
{
   return @@ENTRY_EXPIRY@@;
}

double QFBreakEvenAtR()
{
   return @@BREAK_EVEN_R@@;
}

int QFTrailingKind()
{
   return @@TRAILING_KIND@@;
}

double QFTrailingActivateR()
{
   return @@TRAILING_ACTIVATE_R@@;
}

double QFTrailingDistance()
{
   return @@TRAILING_DISTANCE@@;
}

bool QFFlattenEndOfDay()
{
   return @@FLATTEN_EOD@@;
}

bool QFMaxOneEntryPerDay()
{
   return @@MAX_ONE_ENTRY_PER_DAY@@;
}

int QFMaxTradesPerDay()
{
   return @@MAX_TRADES_PER_DAY@@;
}

bool QFDontTradeOnWeekends()
{
   return @@DONT_TRADE_WEEKENDS@@;
}

bool QFExitOnFriday()
{
   return @@EXIT_ON_FRIDAY@@;
}

int QFBrokerDayKey(const datetime bar_time)
{
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.year*10000+current.mon*100+current.day;
}

bool QFInMandatoryEntryWindow(const datetime bar_time)
{
   // QuantForge entry session, start inclusive and end exclusive, in
   // broker/chart local time. Must match the window the backtest was run with.
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.hour>=InpEntryWindowStartHour && current.hour<InpEntryWindowEndHour;
}

void QFSyncEntryDay(const datetime bar_time)
{
   const int day_key=QFBrokerDayKey(bar_time);
   if(day_key!=g_entry_day_key)
   {
      g_entry_day_key=day_key;
      g_entries_today=0;
   }
}

bool QFEntryDayExhausted(const datetime bar_time)
{
   QFSyncEntryDay(bar_time);
   int cap=0;
   if(QFMaxOneEntryPerDay())
      cap=1;
   else if(QFMaxTradesPerDay()>0)
      cap=QFMaxTradesPerDay();
   if(cap<=0)
      return false;
   return g_entries_today>=cap;
}

void QFMarkEntrySignalTaken(const datetime bar_time)
{
   QFSyncEntryDay(bar_time);
   g_entries_today++;
}

bool QFWeekendBlocked(const datetime bar_time)
{
   if(!QFDontTradeOnWeekends())
      return false;
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.day_of_week==0 || current.day_of_week==6;
}

bool QFFridayFlattenHour(const datetime bar_time)
{
   if(!QFExitOnFriday())
      return false;
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.day_of_week==5 && current.hour>=@@EOD_HOUR@@;
}

int QFPartialCount()
{
   return @@PARTIAL_COUNT@@;
}

double QFPartialAtR(const int index)
{
   @@PARTIAL_AT_R@@
}

double QFPartialFraction(const int index)
{
   @@PARTIAL_FRACTION@@
}

double QFNormalizeVolume(const double requested)
{
   const double minimum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   const double maximum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
   const double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(requested<=0.0 || step<=0.0)
      return 0.0;
   double volume=MathFloor(requested/step+1.0e-12)*step;
   volume=MathMin(volume,maximum);
   if(volume+1.0e-12<minimum)
      return 0.0;
   int digits=0;
   double scaled=step;
   while(digits<8 && MathAbs(scaled-MathRound(scaled))>1.0e-10)
   {
      scaled*=10.0;
      digits++;
   }
   return NormalizeDouble(volume,digits);
}

bool QFApplyPreferredFilling()
{
   ENUM_ORDER_TYPE_FILLING preferred[]={@@FILLING_MODES@@};
   const int count=@@FILLING_MODE_COUNT@@;
   if(count<=0)
      return g_trade.SetTypeFillingBySymbol(_Symbol);
   const long allowed=SymbolInfoInteger(_Symbol,SYMBOL_FILLING_MODE);
   for(int i=0;i<count && i<ArraySize(preferred);i++)
   {
      long flag=0;
      if(preferred[i]==ORDER_FILLING_FOK)
         flag=SYMBOL_FILLING_FOK;
      else if(preferred[i]==ORDER_FILLING_IOC)
         flag=SYMBOL_FILLING_IOC;
      else if(preferred[i]==ORDER_FILLING_RETURN)
         flag=SYMBOL_FILLING_RETURN;
      if(flag!=0 && (allowed&flag)==flag)
      {
         g_trade.SetTypeFilling(preferred[i]);
         return true;
      }
   }
   return g_trade.SetTypeFillingBySymbol(_Symbol);
}

bool QFOpenOrder(const bool buy)
{
   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick))
      return false;
   const double stop_distance=QFStopDistance();
   const double target_distance=QFTargetDistance(stop_distance);
   if(!QFValid(stop_distance) || !QFValid(target_distance)
      || stop_distance<=0.0 || target_distance<=0.0)
      return false;
   const int entry_kind=QFEntryOrderKind();
   const double entry_distance=QFEntryDistance();
   const double limit_offset=QFEntryLimitOffset();
   if(entry_kind!=0 && (!QFValid(entry_distance) || entry_distance<=0.0))
      return false;
   if(entry_kind==3 && (!QFValid(limit_offset) || limit_offset<=0.0))
      return false;
   const double minimum_distance=(double)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL)*_Point;
   if(stop_distance<minimum_distance || target_distance<minimum_distance
      || (entry_kind!=0 && entry_distance<minimum_distance)
      || (entry_kind==3 && limit_offset<minimum_distance))
      return false;

   const double reference=buy ? tick.ask : tick.bid;
   double intended_entry=reference;
   double stop_trigger=0.0;
   if(entry_kind==1)
      intended_entry=buy ? reference+entry_distance : reference-entry_distance;
   else if(entry_kind==2)
      intended_entry=buy ? reference-entry_distance : reference+entry_distance;
   else if(entry_kind==3)
   {
      stop_trigger=buy ? reference+entry_distance : reference-entry_distance;
      intended_entry=buy ? stop_trigger-limit_offset : stop_trigger+limit_offset;
      stop_trigger=NormalizeDouble(stop_trigger,_Digits);
   }
   intended_entry=NormalizeDouble(intended_entry,_Digits);
   const double stop=NormalizeDouble(buy ? intended_entry-stop_distance
                                         : intended_entry+stop_distance,_Digits);
   const double target=NormalizeDouble(buy ? intended_entry+target_distance
                                           : intended_entry-target_distance,_Digits);
   double loss_per_lot=0.0;
   const ENUM_ORDER_TYPE market_type=buy ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
   if(!OrderCalcProfit(market_type,_Symbol,1.0,intended_entry,stop,loss_per_lot))
      return false;
   loss_per_lot=MathAbs(loss_per_lot);
   const double tick_size=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
   const double tick_value=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
   if(tick_size<=0.0 || tick_value<=0.0)
      return false;
   const double slippage_cost=2.0*InpEstimatedSlippagePointsPerSide*_Point/tick_size*tick_value;
   const double risk_per_lot=loss_per_lot+InpCommissionPerLotRoundTurn+slippage_cost;
   if(risk_per_lot<=0.0)
      return false;
   const double volume=QFNormalizeVolume(QFResolveVolume(risk_per_lot));
   if(volume<=0.0)
      return false;

   g_trade.SetExpertMagicNumber(InpMagic);
   g_trade.SetDeviationInPoints(InpDeviationPoints);
   QFApplyPreferredFilling();
   const string comment="QF-@@FINGERPRINT_SHORT@@";
   bool sent=false;
   if(entry_kind==0)
      sent=buy
           ? g_trade.Buy(volume,_Symbol,0.0,stop,target,comment)
           : g_trade.Sell(volume,_Symbol,0.0,stop,target,comment);
   else
   {
      const datetime expiration=iTime(_Symbol,_Period,0)
                                +(datetime)(QFEntryExpiryBars()*PeriodSeconds(_Period));
      if(entry_kind==1)
         sent=buy
              ? g_trade.BuyStop(volume,intended_entry,_Symbol,stop,target,
                                ORDER_TIME_SPECIFIED,expiration,comment)
              : g_trade.SellStop(volume,intended_entry,_Symbol,stop,target,
                                 ORDER_TIME_SPECIFIED,expiration,comment);
      else if(entry_kind==2)
         sent=buy
              ? g_trade.BuyLimit(volume,intended_entry,_Symbol,stop,target,
                                 ORDER_TIME_SPECIFIED,expiration,comment)
              : g_trade.SellLimit(volume,intended_entry,_Symbol,stop,target,
                                  ORDER_TIME_SPECIFIED,expiration,comment);
      else
         sent=buy
              ? g_trade.BuyStopLimit(volume,intended_entry,stop_trigger,_Symbol,stop,target,
                                     ORDER_TIME_SPECIFIED,expiration,comment)
              : g_trade.SellStopLimit(volume,intended_entry,stop_trigger,_Symbol,stop,target,
                                      ORDER_TIME_SPECIFIED,expiration,comment);
   }
   if(!sent)
      Print("QuantForge entry rejected: ",g_trade.ResultRetcodeDescription());
   else if(entry_kind==0)
      g_initial_volume=0.0;
   return sent;
}

bool QFOwnPosition()
{
   if(!PositionSelect(_Symbol))
      return false;
   return (ulong)PositionGetInteger(POSITION_MAGIC)==InpMagic;
}

bool QFOwnPendingOrder()
{
   for(int index=OrdersTotal()-1;index>=0;index--)
   {
      const ulong ticket=OrderGetTicket(index);
      if(ticket==0)
         continue;
      if(OrderGetString(ORDER_SYMBOL)==_Symbol
         && (ulong)OrderGetInteger(ORDER_MAGIC)==InpMagic)
         return true;
   }
   return false;
}

void QFCancelOwnOrders()
{
   for(int index=OrdersTotal()-1;index>=0;index--)
   {
      const ulong ticket=OrderGetTicket(index);
      if(ticket==0)
         continue;
      if(OrderGetString(ORDER_SYMBOL)==_Symbol
         && (ulong)OrderGetInteger(ORDER_MAGIC)==InpMagic
         && !g_trade.OrderDelete(ticket))
         Print("QuantForge pending-order cancellation rejected: ",
               g_trade.ResultRetcodeDescription());
   }
}

void QFResetPositionState()
{
   g_initial_volume=0.0;
   g_initial_risk=0.0;
   g_peak_favorable=EMPTY_VALUE;
   ArrayInitialize(g_partial_done,false);
}

// Fill-aware favorable extreme from completed decision bar's M1 path.
// Entry minute: close only. Later minutes: high/low. Ignores pre-entry minutes.
double QFFavorableSampleSinceEntry(const bool buy)
{
   if(!QFOwnPosition())
      return EMPTY_VALUE;
   const datetime entry=(datetime)PositionGetInteger(POSITION_TIME);
   const int entry_shift=iBarShift(_Symbol,PERIOD_M1,entry,false);
   if(entry_shift<0)
      return EMPTY_VALUE;
   const datetime entry_minute=iTime(_Symbol,PERIOD_M1,entry_shift);
   const datetime completed_start=iTime(_Symbol,_Period,1);
   const datetime completed_end=iTime(_Symbol,_Period,0);
   if(completed_start<=0 || completed_end<=completed_start)
      return EMPTY_VALUE;
   MqlRates rates[];
   const int copied=CopyRates(_Symbol,PERIOD_M1,completed_start,completed_end-1,rates);
   if(copied<=0)
      return EMPTY_VALUE;
   const double completed_spread=(double)iSpread(_Symbol,_Period,1)*_Point;
   double best=EMPTY_VALUE;
   for(int index=0;index<copied;index++)
   {
      if(rates[index].time<entry_minute)
         continue;
      double sample;
      if(rates[index].time==entry_minute)
         sample=rates[index].close;
      else
         sample=buy ? rates[index].high : rates[index].low;
      if(!buy)
         sample+=completed_spread;
      if(best==EMPTY_VALUE)
         best=sample;
      else
         best=buy ? MathMax(best,sample) : MathMin(best,sample);
   }
   return best;
}

void QFRatchetPeakFavorable(const bool buy,const double sample)
{
   if(!QFValid(sample))
      return;
   if(g_peak_favorable==EMPTY_VALUE)
      g_peak_favorable=sample;
   else
      g_peak_favorable=buy ? MathMax(g_peak_favorable,sample)
                           : MathMin(g_peak_favorable,sample);
}

void QFCapturePositionState()
{
   if(!QFOwnPosition() || g_initial_volume>0.0)
      return;
   const double entry=PositionGetDouble(POSITION_PRICE_OPEN);
   const double stop=PositionGetDouble(POSITION_SL);
   g_initial_volume=PositionGetDouble(POSITION_VOLUME);
   g_initial_risk=MathAbs(entry-stop);
   ArrayInitialize(g_partial_done,false);
}

double QFNormalizePartialVolume(const double requested,const double remaining)
{
   const double minimum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   const double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(requested+1.0e-12>=remaining)
      return remaining;
   double volume=MathFloor(requested/step+1.0e-12)*step;
   if(volume+1.0e-12<minimum)
      return 0.0;
   if(remaining-volume+1.0e-12<minimum)
      volume=remaining;
   return QFNormalizeVolume(volume);
}

bool QFClosePartial(const double volume)
{
   if(!QFOwnPosition() || volume<=0.0)
      return false;
   const ENUM_POSITION_TYPE type=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   const long margin_mode=AccountInfoInteger(ACCOUNT_MARGIN_MODE);
   if(margin_mode==ACCOUNT_MARGIN_MODE_RETAIL_HEDGING)
      return g_trade.PositionClosePartial(_Symbol,volume,InpDeviationPoints);
   return type==POSITION_TYPE_BUY
          ? g_trade.Sell(volume,_Symbol,0.0,0.0,0.0,"QF-partial")
          : g_trade.Buy(volume,_Symbol,0.0,0.0,0.0,"QF-partial");
}

bool QFInCloseBlackout()
{
   MqlDateTime current;
   if(!TimeToStruct(iTime(_Symbol,_Period,0),current))
      return false;
   return current.hour>=@@EOD_HOUR@@;
}

bool QFStopWouldTriggerAtOpen(const bool buy,const double candidate,
                              const double bar_open,const double bar_spread)
{
   if(!QFValid(candidate))
      return true;
   return buy ? (bar_open<=candidate+1.0e-12)
              : (bar_open+bar_spread>=candidate-1.0e-12);
}

// Clamp to stops-level, or EMPTY_VALUE if the stop would already trigger at open
// (matches Rust placeable_stop_candidate / MT5 PositionModify reject).
double QFPlaceableStop(const bool buy,const double raw,const double bar_open,
                       const double bar_spread,const double minimum_distance)
{
   if(!QFValid(raw))
      return EMPTY_VALUE;
   const double candidate=buy ? MathMin(raw,bar_open-minimum_distance)
                              : MathMax(raw,bar_open+bar_spread+minimum_distance);
   if(QFStopWouldTriggerAtOpen(buy,candidate,bar_open,bar_spread))
      return EMPTY_VALUE;
   return candidate;
}

bool QFTightenStop(const bool buy,const double candidate,const double target)
{
   const double current=PositionGetDouble(POSITION_SL);
   if(!QFValid(candidate)
      || (buy && candidate<=current+1.0e-12)
      || (!buy && candidate>=current-1.0e-12))
      return false;
   if(!g_trade.PositionModify(_Symbol,NormalizeDouble(candidate,_Digits),target))
   {
      Print("QuantForge stop modification rejected: ",g_trade.ResultRetcodeDescription());
      return false;
   }
   return true;
}

void QFManagePosition()
{
   if(!QFOwnPosition())
   {
      QFResetPositionState();
      return;
   }
   QFCapturePositionState();
   if(g_initial_volume<=0.0 || g_initial_risk<=0.0)
      return;
   const ENUM_POSITION_TYPE type=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   const bool buy=type==POSITION_TYPE_BUY;
   const double entry=PositionGetDouble(POSITION_PRICE_OPEN);
   const double target=PositionGetDouble(POSITION_TP);
   const double sample=QFFavorableSampleSinceEntry(buy);
   QFRatchetPeakFavorable(buy,sample);
   if(!QFValid(g_peak_favorable))
      return;
   const double favorable=g_peak_favorable;
   const double favorable_r=buy ? (favorable-entry)/g_initial_risk
                                : (entry-favorable)/g_initial_risk;
   const double minimum_distance=
      (double)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL)*_Point;
   // Match Rust: placeable stops only — never clamp a through-market trail onto
   // the open (that invents an immediate runner exit MT5 would reject).
   const double bar_open=iOpen(_Symbol,_Period,0);
   const double bar_spread=(double)iSpread(_Symbol,_Period,0)*_Point;

   if(QFBreakEvenAtR()>0.0 && favorable_r>=QFBreakEvenAtR())
   {
      const double candidate=QFPlaceableStop(buy,entry,bar_open,bar_spread,minimum_distance);
      if(QFValid(candidate))
         QFTightenStop(buy,candidate,target);
   }
   if(QFTrailingKind()>0 && favorable_r>=QFTrailingActivateR())
   {
      const double distance=QFTrailingDistance();
      if(QFValid(distance) && distance>0.0)
      {
         const double raw=buy ? favorable-distance : favorable+distance;
         const double candidate=QFPlaceableStop(buy,raw,bar_open,bar_spread,minimum_distance);
         if(QFValid(candidate))
            QFTightenStop(buy,candidate,target);
      }
   }

   for(int index=0;index<QFPartialCount() && QFOwnPosition();index++)
   {
      if(g_partial_done[index] || favorable_r<QFPartialAtR(index))
         continue;
      const double remaining=PositionGetDouble(POSITION_VOLUME);
      const double volume=QFNormalizePartialVolume(
         g_initial_volume*QFPartialFraction(index),remaining);
      if(volume<=0.0)
         continue;
      if(QFClosePartial(volume))
         g_partial_done[index]=true;
      else
         Print("QuantForge partial exit rejected: ",g_trade.ResultRetcodeDescription());
   }
}

bool QFTimeStopReached()
{
   const int limit=@@TIME_STOP@@;
   if(limit<=0 || !QFOwnPosition())
      return false;
   const datetime entry_time=(datetime)PositionGetInteger(POSITION_TIME);
   const int bars_held=iBarShift(_Symbol,_Period,entry_time,false);
   return bars_held>=limit;
}

void QFRecordEquity(const datetime bar_time)
{
   if(g_equity_file==INVALID_HANDLE)
      return;
   const double balance=AccountInfoDouble(ACCOUNT_BALANCE);
   const double equity=AccountInfoDouble(ACCOUNT_EQUITY);
   // A repeated sample can move neither the peak, the drawdown nor the ending
   // balance, so skipping it keeps the parity metrics identical while removing
   // one row per tick from the hot path. OnDeinit still flushes and closes, so
   // per-record flushing only bought crash resilience at a large cost.
   if(g_equity_recorded && balance==g_last_equity_balance && equity==g_last_equity)
      return;
   g_equity_recorded=true;
   g_last_equity_balance=balance;
   g_last_equity=equity;
   FileWrite(g_equity_file,(long)bar_time*1000,balance,equity);
}

int OnInit()
{
   if(_Symbol!="@@SYMBOL@@")
   {
      Print("QuantForge export is broker-bound to @@SYMBOL@@, not ",_Symbol);
      return INIT_PARAMETERS_INCORRECT;
   }
   if(!(bool)MQLInfoInteger(MQL_TESTER) && !InpAllowLiveTrading)
   {
      Print("QuantForge live trading is disabled. Explicitly enable InpAllowLiveTrading only after certification.");
      return INIT_FAILED;
   }
   g_trade.SetExpertMagicNumber(InpMagic);
   g_trade.SetDeviationInPoints(InpDeviationPoints);
   QFApplyPreferredFilling();
   ArrayResize(g_partial_done,QFPartialCount());
   QFResetPositionState();
   g_last_bar=iTime(_Symbol,_Period,0);

   if((bool)MQLInfoInteger(MQL_TESTER) && StringLen(InpParityPrefix)>0)
   {
      FolderCreate("QuantForge",FILE_COMMON);
      g_deals_file=FileOpen(InpParityPrefix+"_deals.csv",
                            FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      g_equity_file=FileOpen(InpParityPrefix+"_equity.csv",
                             FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      g_metadata_file=FileOpen(InpParityPrefix+"_metadata.csv",
                               FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      if(g_deals_file!=INVALID_HANDLE)
         FileWrite(g_deals_file,"deal_ticket","position_id","timestamp_ms","deal_type",
                   "deal_entry","price","volume","profit","commission","swap","fee");
      if(g_equity_file!=INVALID_HANDLE)
         FileWrite(g_equity_file,"timestamp_ms","balance","equity");
      if(g_metadata_file!=INVALID_HANDLE)
      {
         FileWrite(g_metadata_file,"property","value");
         FileWrite(g_metadata_file,"strategy_fingerprint","@@STRATEGY_FINGERPRINT@@");
         FileWrite(g_metadata_file,"broker_spec_hash","@@BROKER_FINGERPRINT@@");
         FileWrite(g_metadata_file,"terminal_build",TerminalInfoInteger(TERMINAL_BUILD));
         FileWrite(g_metadata_file,"broker",AccountInfoString(ACCOUNT_COMPANY));
         FileWrite(g_metadata_file,"server",AccountInfoString(ACCOUNT_SERVER));
         FileWrite(g_metadata_file,"symbol",_Symbol);
         FileWrite(g_metadata_file,"timeframe",EnumToString(_Period));
         FileWrite(g_metadata_file,"magic",InpMagic);
         FileWrite(g_metadata_file,"deviation_points",InpDeviationPoints);
         FileWrite(g_metadata_file,"max_spread_points",InpMaxSpreadPoints);
         FileWrite(g_metadata_file,"estimated_slippage_points_per_side",
                   InpEstimatedSlippagePointsPerSide);
         FileWrite(g_metadata_file,"commission_per_lot_round_turn",
                   InpCommissionPerLotRoundTurn);
         FileWrite(g_metadata_file,"risk_budget",QFRiskBudget());
         FileWrite(g_metadata_file,"initial_deposit",AccountInfoDouble(ACCOUNT_BALANCE));
         FileWrite(g_metadata_file,"account_currency",AccountInfoString(ACCOUNT_CURRENCY));
         // Same token QuantForge uses for bar localization (must match the pack).
         FileWrite(g_metadata_file,"broker_timezone","@@BROKER_TIMEZONE@@");
         FileWrite(g_metadata_file,"server_utc_offset_seconds_at_export",
                   (long)(TimeTradeServer()-TimeGMT()));
         FileWrite(g_metadata_file,"started_server_time",TimeToString(TimeCurrent(),TIME_DATE|TIME_SECONDS));
         FileFlush(g_metadata_file);
      }
   }
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   // Match Scout/Judge EndOfData: flatten any live position before the tester
   // tears down so deals.csv always contains exit legs.
   if(MQLInfoInteger(MQL_TESTER) && QFOwnPosition())
   {
      if(!g_trade.PositionClose(_Symbol,InpDeviationPoints))
         Print("QuantForge end-of-data flatten rejected: ",
               g_trade.ResultRetcodeDescription());
   }
   QFCancelOwnOrders();
   sqReleaseHandles();
   QFXReleaseHandles();
   if(g_deals_file!=INVALID_HANDLE)
   {
      FileFlush(g_deals_file);
      FileClose(g_deals_file);
   }
   if(g_equity_file!=INVALID_HANDLE)
   {
      FileFlush(g_equity_file);
      FileClose(g_equity_file);
   }
   if(g_metadata_file!=INVALID_HANDLE)
   {
      FileWrite(g_metadata_file,"finished_server_time",TimeToString(TimeCurrent(),TIME_DATE|TIME_SECONDS));
      FileFlush(g_metadata_file);
      FileClose(g_metadata_file);
   }
}

void OnTradeTransaction(const MqlTradeTransaction &transaction,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result)
{
   if(transaction.type!=TRADE_TRANSACTION_DEAL_ADD || transaction.deal==0
      || !HistoryDealSelect(transaction.deal))
      return;
   if((ulong)HistoryDealGetInteger(transaction.deal,DEAL_MAGIC)!=InpMagic)
      return;
   const ENUM_DEAL_ENTRY deal_entry=
      (ENUM_DEAL_ENTRY)HistoryDealGetInteger(transaction.deal,DEAL_ENTRY);
   if(deal_entry==DEAL_ENTRY_IN)
   {
      g_initial_volume=0.0;
      QFCapturePositionState();
      // First fill locks the broker day (pending place alone does not).
      QFMarkEntrySignalTaken(iTime(_Symbol,_Period,0));
   }
   if(deal_entry==DEAL_ENTRY_OUT || deal_entry==DEAL_ENTRY_OUT_BY)
   {
      const double deal_profit=HistoryDealGetDouble(transaction.deal,DEAL_PROFIT)
         +HistoryDealGetDouble(transaction.deal,DEAL_SWAP)
         +HistoryDealGetDouble(transaction.deal,DEAL_COMMISSION)
         +HistoryDealGetDouble(transaction.deal,DEAL_FEE);
      if(deal_profit<0.0)
         g_loss_streak++;
      else if(deal_profit>0.0)
         g_loss_streak=0;
      g_last_exit_bar=iTime(_Symbol,_Period,0);
      if(!QFOwnPosition())
         QFResetPositionState();
   }
   if(g_deals_file==INVALID_HANDLE)
      return;
   FileWrite(g_deals_file,
             transaction.deal,
             (ulong)HistoryDealGetInteger(transaction.deal,DEAL_POSITION_ID),
             (long)HistoryDealGetInteger(transaction.deal,DEAL_TIME_MSC),
             EnumToString((ENUM_DEAL_TYPE)HistoryDealGetInteger(transaction.deal,DEAL_TYPE)),
             EnumToString(deal_entry),
             HistoryDealGetDouble(transaction.deal,DEAL_PRICE),
             HistoryDealGetDouble(transaction.deal,DEAL_VOLUME),
             HistoryDealGetDouble(transaction.deal,DEAL_PROFIT),
             HistoryDealGetDouble(transaction.deal,DEAL_COMMISSION),
             HistoryDealGetDouble(transaction.deal,DEAL_SWAP),
             HistoryDealGetDouble(transaction.deal,DEAL_FEE));
   FileFlush(g_deals_file);
}

void OnTick()
{
   checkBarOpen();
   const datetime current_bar=iTime(_Symbol,_Period,0);
   if(current_bar<=0)
      return;
   if(_sqIsBarOpen)
      g_decision_bars_seen++;

   if((QFFlattenEndOfDay() && QFInCloseBlackout()) || QFFridayFlattenHour(current_bar))
   {
      QFCancelOwnOrders();
      if(QFOwnPosition()
         && !g_trade.PositionClose(_Symbol,InpDeviationPoints))
         Print("QuantForge end-of-day exit rejected: ",
               g_trade.ResultRetcodeDescription());
      QFRecordEquity(current_bar);
      return;
   }

   // Hard session: cancel unfilled pending outside [02:00, 19:00).
   if(!QFInMandatoryEntryWindow(current_bar))
      QFCancelOwnOrders();

   QFManagePosition();

   if(QFOwnPosition() && (QFExitSignal(0) || QFTimeStopReached()))
   {
      if(!g_trade.PositionClose(_Symbol,InpDeviationPoints))
         Print("QuantForge exit rejected: ",g_trade.ResultRetcodeDescription());
      QFRecordEquity(current_bar);
      return;
   }
   if(PositionSelect(_Symbol) || QFOwnPendingOrder() || !QFFilters(0))
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(g_last_exit_bar==current_bar)
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(QFWeekendBlocked(current_bar))
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(!QFInMandatoryEntryWindow(current_bar))
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(!_sqIsBarOpen)
   {
      QFRecordEquity(current_bar);
      return;
   }
   // MT5 retains pre-test indicator history while QuantForge packs begin at
   // the selected date. Wait for the shared recursive-buffer convergence gate.
   if(g_decision_bars_seen<320)
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(QFEntryDayExhausted(current_bar))
   {
      QFRecordEquity(current_bar);
      return;
   }

   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick))
      return;
   const double spread_points=(tick.ask-tick.bid)/_Point;
   if(InpMaxSpreadPoints>0.0 && spread_points>InpMaxSpreadPoints)
   {
      QFRecordEquity(current_bar);
      return;
   }

   LongEntrySignal=QFLongSignal(0);
   ShortEntrySignal=QFShortSignal(0);
   const bool long_signal=LongEntrySignal;
   const bool short_signal=ShortEntrySignal;
   if(long_signal!=short_signal)
   {
      // Place only; day lock happens on fill (DEAL_ENTRY_IN / market position).
      if(QFOpenOrder(long_signal))
      {
         QFCapturePositionState();
         if(QFOwnPosition())
            QFMarkEntrySignalTaken(current_bar);
      }
   }
   QFRecordEquity(current_bar);
}
