#property strict
#property version   "1.00"
#property description "Generated by QuantForge from typed Strategy IR."

#include <Trade/Trade.mqh>

input bool   InpAllowLiveTrading=@@ALLOW_LIVE@@;
input ulong  InpMagic=@@MAGIC@@;
input int    InpDeviationPoints=@@DEVIATION@@;
input double InpMaxSpreadPoints=@@MAX_SPREAD@@;
input double InpEstimatedSlippagePointsPerSide=@@SLIPPAGE@@;
input double InpCommissionPerLotRoundTurn=@@COMMISSION@@;
input string InpParityPrefix="@@PARITY_PREFIX@@";

CTrade g_trade;
datetime g_last_bar=0;
datetime g_last_exit_bar=0;
int g_entry_day_key=0;
int g_entries_today=0;
int g_deals_file=INVALID_HANDLE;
int g_equity_file=INVALID_HANDLE;
int g_metadata_file=INVALID_HANDLE;
double g_initial_volume=0.0;
double g_initial_risk=0.0;
bool g_partial_done[];

// Strategy fingerprint: @@STRATEGY_FINGERPRINT@@
// Broker specification hash: @@BROKER_FINGERPRINT@@

bool QFValid(const double value)
{
   return value!=EMPTY_VALUE && MathIsValidNumber(value);
}

double QFPrice(const int field,const int shift)
{
   if(shift<0 || Bars(_Symbol,_Period)<=shift)
      return EMPTY_VALUE;
   if(field==0) return iOpen(_Symbol,_Period,shift);
   if(field==1) return iHigh(_Symbol,_Period,shift);
   if(field==2) return iLow(_Symbol,_Period,shift);
   return iClose(_Symbol,_Period,shift);
}

double QFBufferValue(const int handle,const int shift)
{
   if(handle==INVALID_HANDLE || shift<0)
      return EMPTY_VALUE;
   double values[1];
   const int copied=CopyBuffer(handle,0,shift,1,values);
   IndicatorRelease(handle);
   if(copied!=1)
      return EMPTY_VALUE;
   return values[0];
}

double QFMA(const ENUM_MA_METHOD method,const ENUM_APPLIED_PRICE source,
            const int period,const int shift)
{
   return QFBufferValue(iMA(_Symbol,_Period,period,0,method,source),shift);
}

double QFRSI(const ENUM_APPLIED_PRICE source,const int period,const int shift)
{
   return QFBufferValue(iRSI(_Symbol,_Period,period,source),shift);
}

double QFATR(const int period,const int shift)
{
   return QFBufferValue(iATR(_Symbol,_Period,period),shift);
}

double QFStdDev(const ENUM_APPLIED_PRICE source,const int period,const int shift)
{
   return QFBufferValue(iStdDev(_Symbol,_Period,period,0,MODE_SMA,source),shift);
}

double QFExtreme(const ENUM_SERIESMODE mode,const int field,const int period,const int shift,
                 const bool maximum)
{
   const int index=maximum
                   ? iHighest(_Symbol,_Period,mode,period,shift)
                   : iLowest(_Symbol,_Period,mode,period,shift);
   if(index<0)
      return EMPTY_VALUE;
   return QFPrice(field,index);
}

double QFZScore(const int field,const ENUM_APPLIED_PRICE source,
                const int period,const int shift)
{
   const double value=QFPrice(field,shift);
   const double mean=QFMA(MODE_SMA,source,period,shift);
   const double deviation=QFStdDev(source,period,shift);
   if(!QFValid(value) || !QFValid(mean) || !QFValid(deviation) || deviation<=0.0)
      return EMPTY_VALUE;
   return (value-mean)/deviation;
}

double QFPercentile(const int field,const ENUM_SERIESMODE mode,
                    const int period,const int shift)
{
   const double value=QFPrice(field,shift);
   const double low=QFExtreme(mode,field,period,shift,false);
   const double high=QFExtreme(mode,field,period,shift,true);
   if(!QFValid(value) || !QFValid(low) || !QFValid(high) || high<=low)
      return EMPTY_VALUE;
   return (value-low)/(high-low)*100.0;
}

double QFROC(const int field,const int period,const int shift)
{
   const double current=QFPrice(field,shift);
   const double previous=QFPrice(field,shift+period);
   if(!QFValid(current) || !QFValid(previous) || previous==0.0)
      return EMPTY_VALUE;
   return (current/previous-1.0)*100.0;
}

double QFAverageRange(const int period,const int shift)
{
   if(period<1 || Bars(_Symbol,_Period)<shift+period)
      return EMPTY_VALUE;
   double sum=0.0;
   for(int index=shift;index<shift+period;index++)
      sum+=iHigh(_Symbol,_Period,index)-iLow(_Symbol,_Period,index);
   return sum/(double)period;
}

double QFContext(const int field,const int shift)
{
   const datetime value=iTime(_Symbol,_Period,shift);
   if(value<=0)
      return EMPTY_VALUE;
   MqlDateTime parts;
   if(!TimeToStruct(value,parts))
      return EMPTY_VALUE;
   return field==0 ? (double)parts.hour : (double)parts.day_of_week;
}

bool QFGreater(const double left,const double right)
{
   return QFValid(left) && QFValid(right) && left>right;
}

bool QFLess(const double left,const double right)
{
   return QFValid(left) && QFValid(right) && left<right;
}

bool QFBetween(const double value,const double lower,const double upper)
{
   return QFValid(value) && QFValid(lower) && QFValid(upper)
          && value>=lower && value<=upper;
}

bool QFCrossAbove(const double current_left,const double current_right,
                  const double previous_left,const double previous_right)
{
   return QFValid(current_left) && QFValid(current_right)
          && QFValid(previous_left) && QFValid(previous_right)
          && current_left>current_right && previous_left<=previous_right;
}

bool QFCrossBelow(const double current_left,const double current_right,
                  const double previous_left,const double previous_right)
{
   return QFValid(current_left) && QFValid(current_right)
          && QFValid(previous_left) && QFValid(previous_right)
          && current_left<current_right && previous_left>=previous_right;
}

bool QFLongSignal(const int extra_shift)
{
   return @@LONG_SIGNAL@@;
}

bool QFShortSignal(const int extra_shift)
{
   return @@SHORT_SIGNAL@@;
}

bool QFExitSignal(const int extra_shift)
{
   return @@EXIT_SIGNAL@@;
}

bool QFFilters(const int extra_shift)
{
   return @@FILTERS@@;
}

double QFStopDistance()
{
   return @@STOP_DISTANCE@@;
}

double QFTargetDistance(const double stop_distance)
{
   return @@TARGET_DISTANCE@@;
}

double QFRiskBudget()
{
   return @@RISK_BUDGET@@;
}

int QFEntryOrderKind()
{
   return @@ENTRY_ORDER_KIND@@;
}

double QFEntryDistance()
{
   return @@ENTRY_DISTANCE@@;
}

int QFEntryExpiryBars()
{
   return @@ENTRY_EXPIRY@@;
}

double QFBreakEvenAtR()
{
   return @@BREAK_EVEN_R@@;
}

int QFTrailingKind()
{
   return @@TRAILING_KIND@@;
}

double QFTrailingActivateR()
{
   return @@TRAILING_ACTIVATE_R@@;
}

double QFTrailingDistance()
{
   return @@TRAILING_DISTANCE@@;
}

bool QFFlattenEndOfDay()
{
   return @@FLATTEN_EOD@@;
}

bool QFMaxOneEntryPerDay()
{
   return @@MAX_ONE_ENTRY_PER_DAY@@;
}

int QFBrokerDayKey(const datetime bar_time)
{
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.year*10000+current.mon*100+current.day;
}

bool QFInMandatoryEntryWindow(const datetime bar_time)
{
   // Hard-coded QuantForge session: [02:00, 19:00) broker/chart local time.
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.hour>=2 && current.hour<19;
}

void QFSyncEntryDay(const datetime bar_time)
{
   const int day_key=QFBrokerDayKey(bar_time);
   if(day_key!=g_entry_day_key)
   {
      g_entry_day_key=day_key;
      g_entries_today=0;
   }
}

bool QFEntryDayExhausted(const datetime bar_time)
{
   if(!QFMaxOneEntryPerDay())
      return false;
   QFSyncEntryDay(bar_time);
   return g_entries_today>=1;
}

void QFMarkEntrySignalTaken(const datetime bar_time)
{
   QFSyncEntryDay(bar_time);
   g_entries_today=1;
}

int QFPartialCount()
{
   return @@PARTIAL_COUNT@@;
}

double QFPartialAtR(const int index)
{
   @@PARTIAL_AT_R@@
}

double QFPartialFraction(const int index)
{
   @@PARTIAL_FRACTION@@
}

double QFNormalizeVolume(const double requested)
{
   const double minimum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   const double maximum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
   const double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(requested<=0.0 || step<=0.0)
      return 0.0;
   double volume=MathFloor(requested/step+1.0e-12)*step;
   volume=MathMin(volume,maximum);
   if(volume+1.0e-12<minimum)
      return 0.0;
   int digits=0;
   double scaled=step;
   while(digits<8 && MathAbs(scaled-MathRound(scaled))>1.0e-10)
   {
      scaled*=10.0;
      digits++;
   }
   return NormalizeDouble(volume,digits);
}

bool QFOpenOrder(const bool buy)
{
   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick))
      return false;
   const double stop_distance=QFStopDistance();
   const double target_distance=QFTargetDistance(stop_distance);
   if(!QFValid(stop_distance) || !QFValid(target_distance)
      || stop_distance<=0.0 || target_distance<=0.0)
      return false;
   const int entry_kind=QFEntryOrderKind();
   const double entry_distance=QFEntryDistance();
   if(entry_kind!=0 && (!QFValid(entry_distance) || entry_distance<=0.0))
      return false;
   const double minimum_distance=(double)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL)*_Point;
   if(stop_distance<minimum_distance || target_distance<minimum_distance
      || (entry_kind!=0 && entry_distance<minimum_distance))
      return false;

   const double reference=buy ? tick.ask : tick.bid;
   double intended_entry=reference;
   if(entry_kind==1)
      intended_entry=buy ? reference+entry_distance : reference-entry_distance;
   else if(entry_kind==2)
      intended_entry=buy ? reference-entry_distance : reference+entry_distance;
   intended_entry=NormalizeDouble(intended_entry,_Digits);
   const double stop=NormalizeDouble(buy ? intended_entry-stop_distance
                                         : intended_entry+stop_distance,_Digits);
   const double target=NormalizeDouble(buy ? intended_entry+target_distance
                                           : intended_entry-target_distance,_Digits);
   double loss_per_lot=0.0;
   const ENUM_ORDER_TYPE market_type=buy ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
   if(!OrderCalcProfit(market_type,_Symbol,1.0,intended_entry,stop,loss_per_lot))
      return false;
   loss_per_lot=MathAbs(loss_per_lot);
   const double tick_size=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
   const double tick_value=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
   if(tick_size<=0.0 || tick_value<=0.0)
      return false;
   const double slippage_cost=2.0*InpEstimatedSlippagePointsPerSide*_Point/tick_size*tick_value;
   const double risk_per_lot=loss_per_lot+InpCommissionPerLotRoundTurn+slippage_cost;
   if(risk_per_lot<=0.0)
      return false;
   const double volume=QFNormalizeVolume(QFRiskBudget()/risk_per_lot);
   if(volume<=0.0)
      return false;

   g_trade.SetExpertMagicNumber(InpMagic);
   g_trade.SetDeviationInPoints(InpDeviationPoints);
   g_trade.SetTypeFillingBySymbol(_Symbol);
   const string comment="QF-@@FINGERPRINT_SHORT@@";
   bool sent=false;
   if(entry_kind==0)
      sent=buy
           ? g_trade.Buy(volume,_Symbol,0.0,stop,target,comment)
           : g_trade.Sell(volume,_Symbol,0.0,stop,target,comment);
   else
   {
      const datetime expiration=iTime(_Symbol,_Period,0)
                                +(datetime)(QFEntryExpiryBars()*PeriodSeconds(_Period));
      if(entry_kind==1)
         sent=buy
              ? g_trade.BuyStop(volume,intended_entry,_Symbol,stop,target,
                                ORDER_TIME_SPECIFIED,expiration,comment)
              : g_trade.SellStop(volume,intended_entry,_Symbol,stop,target,
                                 ORDER_TIME_SPECIFIED,expiration,comment);
      else
         sent=buy
              ? g_trade.BuyLimit(volume,intended_entry,_Symbol,stop,target,
                                 ORDER_TIME_SPECIFIED,expiration,comment)
              : g_trade.SellLimit(volume,intended_entry,_Symbol,stop,target,
                                  ORDER_TIME_SPECIFIED,expiration,comment);
   }
   if(!sent)
      Print("QuantForge entry rejected: ",g_trade.ResultRetcodeDescription());
   else if(entry_kind==0)
      g_initial_volume=0.0;
   return sent;
}

bool QFOwnPosition()
{
   if(!PositionSelect(_Symbol))
      return false;
   return (ulong)PositionGetInteger(POSITION_MAGIC)==InpMagic;
}

bool QFOwnPendingOrder()
{
   for(int index=OrdersTotal()-1;index>=0;index--)
   {
      const ulong ticket=OrderGetTicket(index);
      if(ticket==0)
         continue;
      if(OrderGetString(ORDER_SYMBOL)==_Symbol
         && (ulong)OrderGetInteger(ORDER_MAGIC)==InpMagic)
         return true;
   }
   return false;
}

void QFCancelOwnOrders()
{
   for(int index=OrdersTotal()-1;index>=0;index--)
   {
      const ulong ticket=OrderGetTicket(index);
      if(ticket==0)
         continue;
      if(OrderGetString(ORDER_SYMBOL)==_Symbol
         && (ulong)OrderGetInteger(ORDER_MAGIC)==InpMagic
         && !g_trade.OrderDelete(ticket))
         Print("QuantForge pending-order cancellation rejected: ",
               g_trade.ResultRetcodeDescription());
   }
}

void QFResetPositionState()
{
   g_initial_volume=0.0;
   g_initial_risk=0.0;
   ArrayInitialize(g_partial_done,false);
}

void QFCapturePositionState()
{
   if(!QFOwnPosition() || g_initial_volume>0.0)
      return;
   const double entry=PositionGetDouble(POSITION_PRICE_OPEN);
   const double stop=PositionGetDouble(POSITION_SL);
   g_initial_volume=PositionGetDouble(POSITION_VOLUME);
   g_initial_risk=MathAbs(entry-stop);
   ArrayInitialize(g_partial_done,false);
}

double QFNormalizePartialVolume(const double requested,const double remaining)
{
   const double minimum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   const double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(requested+1.0e-12>=remaining)
      return remaining;
   double volume=MathFloor(requested/step+1.0e-12)*step;
   if(volume+1.0e-12<minimum)
      return 0.0;
   if(remaining-volume+1.0e-12<minimum)
      volume=remaining;
   return QFNormalizeVolume(volume);
}

bool QFClosePartial(const double volume)
{
   if(!QFOwnPosition() || volume<=0.0)
      return false;
   const ENUM_POSITION_TYPE type=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   const long margin_mode=AccountInfoInteger(ACCOUNT_MARGIN_MODE);
   if(margin_mode==ACCOUNT_MARGIN_MODE_RETAIL_HEDGING)
      return g_trade.PositionClosePartial(_Symbol,volume,InpDeviationPoints);
   return type==POSITION_TYPE_BUY
          ? g_trade.Sell(volume,_Symbol,0.0,0.0,0.0,"QF-partial")
          : g_trade.Buy(volume,_Symbol,0.0,0.0,0.0,"QF-partial");
}

bool QFInCloseBlackout()
{
   MqlDateTime current;
   if(!TimeToStruct(iTime(_Symbol,_Period,0),current))
      return false;
   return current.hour>=22;
}

bool QFTightenStop(const bool buy,const double candidate,const double target)
{
   const double current=PositionGetDouble(POSITION_SL);
   if(!QFValid(candidate)
      || (buy && candidate<=current+1.0e-12)
      || (!buy && candidate>=current-1.0e-12))
      return false;
   if(!g_trade.PositionModify(_Symbol,NormalizeDouble(candidate,_Digits),target))
   {
      Print("QuantForge stop modification rejected: ",g_trade.ResultRetcodeDescription());
      return false;
   }
   return true;
}

void QFManagePosition()
{
   if(!QFOwnPosition())
   {
      QFResetPositionState();
      return;
   }
   QFCapturePositionState();
   if(g_initial_volume<=0.0 || g_initial_risk<=0.0)
      return;
   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick))
      return;
   const ENUM_POSITION_TYPE type=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   const bool buy=type==POSITION_TYPE_BUY;
   const double entry=PositionGetDouble(POSITION_PRICE_OPEN);
   const double target=PositionGetDouble(POSITION_TP);
   const double completed_spread=(double)iSpread(_Symbol,_Period,1)*_Point;
   const double favorable=buy ? iHigh(_Symbol,_Period,1)
                              : iLow(_Symbol,_Period,1)+completed_spread;
   const double favorable_r=buy ? (favorable-entry)/g_initial_risk
                                : (entry-favorable)/g_initial_risk;
   const double minimum_distance=
      (double)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL)*_Point;

   if(QFBreakEvenAtR()>0.0 && favorable_r>=QFBreakEvenAtR())
   {
      const double candidate=buy ? MathMin(entry,tick.bid-minimum_distance)
                                 : MathMax(entry,tick.ask+minimum_distance);
      QFTightenStop(buy,candidate,target);
   }
   if(QFTrailingKind()>0 && favorable_r>=QFTrailingActivateR())
   {
      const double distance=QFTrailingDistance();
      if(QFValid(distance) && distance>0.0)
      {
         double candidate=buy ? favorable-distance : favorable+distance;
         candidate=buy ? MathMin(candidate,tick.bid-minimum_distance)
                       : MathMax(candidate,tick.ask+minimum_distance);
         QFTightenStop(buy,candidate,target);
      }
   }

   for(int index=0;index<QFPartialCount() && QFOwnPosition();index++)
   {
      if(g_partial_done[index] || favorable_r<QFPartialAtR(index))
         continue;
      const double remaining=PositionGetDouble(POSITION_VOLUME);
      const double volume=QFNormalizePartialVolume(
         g_initial_volume*QFPartialFraction(index),remaining);
      if(volume<=0.0)
         continue;
      if(QFClosePartial(volume))
         g_partial_done[index]=true;
      else
         Print("QuantForge partial exit rejected: ",g_trade.ResultRetcodeDescription());
   }
}

bool QFTimeStopReached()
{
   const int limit=@@TIME_STOP@@;
   if(limit<=0 || !QFOwnPosition())
      return false;
   const datetime entry_time=(datetime)PositionGetInteger(POSITION_TIME);
   const int bars_held=iBarShift(_Symbol,_Period,entry_time,false);
   return bars_held>=limit;
}

void QFRecordEquity(const datetime bar_time)
{
   if(g_equity_file==INVALID_HANDLE)
      return;
   FileWrite(g_equity_file,(long)bar_time*1000,
             AccountInfoDouble(ACCOUNT_BALANCE),
             AccountInfoDouble(ACCOUNT_EQUITY));
   FileFlush(g_equity_file);
}

int OnInit()
{
   if(_Symbol!="@@SYMBOL@@")
   {
      Print("QuantForge export is broker-bound to @@SYMBOL@@, not ",_Symbol);
      return INIT_PARAMETERS_INCORRECT;
   }
   if(!(bool)MQLInfoInteger(MQL_TESTER) && !InpAllowLiveTrading)
   {
      Print("QuantForge live trading is disabled. Explicitly enable InpAllowLiveTrading only after certification.");
      return INIT_FAILED;
   }
   g_trade.SetExpertMagicNumber(InpMagic);
   g_trade.SetDeviationInPoints(InpDeviationPoints);
   g_trade.SetTypeFillingBySymbol(_Symbol);
   ArrayResize(g_partial_done,QFPartialCount());
   QFResetPositionState();
   g_last_bar=iTime(_Symbol,_Period,0);

   if((bool)MQLInfoInteger(MQL_TESTER) && StringLen(InpParityPrefix)>0)
   {
      FolderCreate("QuantForge",FILE_COMMON);
      g_deals_file=FileOpen(InpParityPrefix+"_deals.csv",
                            FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      g_equity_file=FileOpen(InpParityPrefix+"_equity.csv",
                             FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      g_metadata_file=FileOpen(InpParityPrefix+"_metadata.csv",
                               FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      if(g_deals_file!=INVALID_HANDLE)
         FileWrite(g_deals_file,"deal_ticket","position_id","timestamp_ms","deal_type",
                   "deal_entry","price","volume","profit","commission","swap","fee");
      if(g_equity_file!=INVALID_HANDLE)
         FileWrite(g_equity_file,"timestamp_ms","balance","equity");
      if(g_metadata_file!=INVALID_HANDLE)
      {
         FileWrite(g_metadata_file,"property","value");
         FileWrite(g_metadata_file,"strategy_fingerprint","@@STRATEGY_FINGERPRINT@@");
         FileWrite(g_metadata_file,"broker_spec_hash","@@BROKER_FINGERPRINT@@");
         FileWrite(g_metadata_file,"terminal_build",TerminalInfoInteger(TERMINAL_BUILD));
         FileWrite(g_metadata_file,"broker",AccountInfoString(ACCOUNT_COMPANY));
         FileWrite(g_metadata_file,"server",AccountInfoString(ACCOUNT_SERVER));
         FileWrite(g_metadata_file,"symbol",_Symbol);
         FileWrite(g_metadata_file,"timeframe",EnumToString(_Period));
         FileWrite(g_metadata_file,"magic",InpMagic);
         FileWrite(g_metadata_file,"initial_deposit",AccountInfoDouble(ACCOUNT_BALANCE));
         FileWrite(g_metadata_file,"account_currency",AccountInfoString(ACCOUNT_CURRENCY));
         FileWrite(g_metadata_file,"started_server_time",TimeToString(TimeCurrent(),TIME_DATE|TIME_SECONDS));
         FileFlush(g_metadata_file);
      }
   }
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   if(g_deals_file!=INVALID_HANDLE)
   {
      FileFlush(g_deals_file);
      FileClose(g_deals_file);
   }
   if(g_equity_file!=INVALID_HANDLE)
   {
      FileFlush(g_equity_file);
      FileClose(g_equity_file);
   }
   if(g_metadata_file!=INVALID_HANDLE)
   {
      FileWrite(g_metadata_file,"finished_server_time",TimeToString(TimeCurrent(),TIME_DATE|TIME_SECONDS));
      FileFlush(g_metadata_file);
      FileClose(g_metadata_file);
   }
}

void OnTradeTransaction(const MqlTradeTransaction &transaction,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result)
{
   if(transaction.type!=TRADE_TRANSACTION_DEAL_ADD || transaction.deal==0
      || !HistoryDealSelect(transaction.deal))
      return;
   if((ulong)HistoryDealGetInteger(transaction.deal,DEAL_MAGIC)!=InpMagic)
      return;
   const ENUM_DEAL_ENTRY deal_entry=
      (ENUM_DEAL_ENTRY)HistoryDealGetInteger(transaction.deal,DEAL_ENTRY);
   if(deal_entry==DEAL_ENTRY_IN)
   {
      g_initial_volume=0.0;
      QFCapturePositionState();
   }
   if(deal_entry==DEAL_ENTRY_OUT || deal_entry==DEAL_ENTRY_OUT_BY)
   {
      g_last_exit_bar=iTime(_Symbol,_Period,0);
      if(!QFOwnPosition())
         QFResetPositionState();
   }
   if(g_deals_file==INVALID_HANDLE)
      return;
   FileWrite(g_deals_file,
             transaction.deal,
             (ulong)HistoryDealGetInteger(transaction.deal,DEAL_POSITION_ID),
             (long)HistoryDealGetInteger(transaction.deal,DEAL_TIME_MSC),
             EnumToString((ENUM_DEAL_TYPE)HistoryDealGetInteger(transaction.deal,DEAL_TYPE)),
             EnumToString(deal_entry),
             HistoryDealGetDouble(transaction.deal,DEAL_PRICE),
             HistoryDealGetDouble(transaction.deal,DEAL_VOLUME),
             HistoryDealGetDouble(transaction.deal,DEAL_PROFIT),
             HistoryDealGetDouble(transaction.deal,DEAL_COMMISSION),
             HistoryDealGetDouble(transaction.deal,DEAL_SWAP),
             HistoryDealGetDouble(transaction.deal,DEAL_FEE));
   FileFlush(g_deals_file);
}

void OnTick()
{
   const datetime current_bar=iTime(_Symbol,_Period,0);
   if(current_bar<=0 || current_bar==g_last_bar)
      return;
   g_last_bar=current_bar;

   if(QFFlattenEndOfDay() && QFInCloseBlackout())
   {
      QFCancelOwnOrders();
      if(QFOwnPosition()
         && !g_trade.PositionClose(_Symbol,InpDeviationPoints))
         Print("QuantForge end-of-day exit rejected: ",
               g_trade.ResultRetcodeDescription());
      QFRecordEquity(current_bar);
      return;
   }

   // Hard session: cancel unfilled pending outside [02:00, 19:00).
   if(!QFInMandatoryEntryWindow(current_bar))
      QFCancelOwnOrders();

   QFManagePosition();

   if(QFOwnPosition() && (QFExitSignal(0) || QFTimeStopReached()))
   {
      if(!g_trade.PositionClose(_Symbol,InpDeviationPoints))
         Print("QuantForge exit rejected: ",g_trade.ResultRetcodeDescription());
      QFRecordEquity(current_bar);
      return;
   }
   if(PositionSelect(_Symbol) || QFOwnPendingOrder() || !QFFilters(0))
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(g_last_exit_bar==current_bar)
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(!QFInMandatoryEntryWindow(current_bar))
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(QFEntryDayExhausted(current_bar))
   {
      QFRecordEquity(current_bar);
      return;
   }

   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick))
      return;
   const double spread_points=(tick.ask-tick.bid)/_Point;
   if(InpMaxSpreadPoints>0.0 && spread_points>InpMaxSpreadPoints)
   {
      QFRecordEquity(current_bar);
      return;
   }

   const bool long_signal=QFLongSignal(0);
   const bool short_signal=QFShortSignal(0);
   if(long_signal!=short_signal)
   {
      // First successful market/pending place locks the broker day.
      if(QFOpenOrder(long_signal))
      {
         QFMarkEntrySignalTaken(current_bar);
         QFCapturePositionState();
      }
   }
   QFRecordEquity(current_bar);
}
