//+------------------------------------------------------------------+
//| QFStopLimitGolden EA
//|
//|    Generated by QuantForge SQX-style export for MetaTrader5
//|    Strategy fingerprint: c1caf5c06cbc15e55c971b7ed6d172fda5ab65fa5732447e9300333b7609b2f6
//+------------------------------------------------------------------+

#property copyright "QuantForge"
#property link      "https://quantforge.local"
#property strict
#property version   "1.00"
#property description "QuantForge SQX-style Strategy IR export."

#property tester_indicator "SqATR"
#property tester_indicator "SqADX"
#property tester_indicator "SqSupplyDemand"
#property tester_indicator "SqStochastic"
#property tester_indicator "SqROC"
#property tester_indicator "SqHighest"
#property tester_indicator "SqLowest"
#property tester_indicator "SqZScore"
#property tester_indicator "SqATRPercentile"
#property tester_indicator "SqLiquiditySweep"
#property tester_indicator "SqOpeningRange"

#include <Trade/Trade.mqh>

// Runtime helpers are inlined so a lone .mq5 still compiles if the sibling
// sqx_runtime.mqh was not copied into Experts/.
// QuantForge SQX-style runtime helpers.
// Bar-open timing and indicator access aligned with StrategyQuant MT5 exports.



datetime g_sq_last_bar_time=0;
bool _sqIsBarOpen=false;

void checkBarOpen()
{
   const datetime current_bar_time=iTime(_Symbol,_Period,1);
   _sqIsBarOpen=false;
   if(current_bar_time<=0)
      return;
   if(g_sq_last_bar_time==0)
   {
      g_sq_last_bar_time=current_bar_time;
      _sqIsBarOpen=true;
      return;
   }
   if(current_bar_time!=g_sq_last_bar_time)
   {
      g_sq_last_bar_time=current_bar_time;
      _sqIsBarOpen=true;
   }
}

bool sqValid(const double value)
{
   return value!=EMPTY_VALUE && MathIsValidNumber(value);
}

bool sqGreater(const double left,const double right)
{
   return sqValid(left) && sqValid(right) && left>right;
}

bool sqLess(const double left,const double right)
{
   return sqValid(left) && sqValid(right) && left<right;
}

bool sqCrossAbove(const double current_left,const double current_right,
                  const double previous_left,const double previous_right)
{
   return sqValid(current_left) && sqValid(current_right)
          && sqValid(previous_left) && sqValid(previous_right)
          && current_left>current_right && previous_left<=previous_right;
}

bool sqCrossBelow(const double current_left,const double current_right,
                  const double previous_left,const double previous_right)
{
   return sqValid(current_left) && sqValid(current_right)
          && sqValid(previous_left) && sqValid(previous_right)
          && current_left<current_right && previous_left>=previous_right;
}

double sqBufferValue(const int handle,const int shift)
{
   if(handle==INVALID_HANDLE || shift<0)
      return EMPTY_VALUE;
   double values[1];
   if(CopyBuffer(handle,0,shift,1,values)!=1)
      return EMPTY_VALUE;
   return values[0];
}

// Indicator handles are cached for the life of the run.  Creating and releasing
// a handle per condition atom forces MT5 to rebuild the indicator's history on
// every tick, which dwarfs the cost of the strategy logic itself and is the main
// reason a generated expert crawls in the Strategy Tester.
#define SQ_MAX_INDICATOR_HANDLES 64

string g_sq_handle_keys[SQ_MAX_INDICATOR_HANDLES];
int    g_sq_handle_values[SQ_MAX_INDICATOR_HANDLES];
int    g_sq_handle_count=0;

int sqHandleSlot(const string key)
{
   for(int index=0;index<g_sq_handle_count;index++)
      if(g_sq_handle_keys[index]==key)
         return index;
   return -1;
}

int sqRemember(const string key,const int handle)
{
   if(g_sq_handle_count<SQ_MAX_INDICATOR_HANDLES)
   {
      g_sq_handle_keys[g_sq_handle_count]=key;
      g_sq_handle_values[g_sq_handle_count]=handle;
      g_sq_handle_count++;
   }
   return handle;
}

void sqReleaseHandles()
{
   for(int index=0;index<g_sq_handle_count;index++)
      if(g_sq_handle_values[index]!=INVALID_HANDLE)
         IndicatorRelease(g_sq_handle_values[index]);
   g_sq_handle_count=0;
}

int sqCustomHandle(const string name,const int first)
{
   const string key=name+"|"+IntegerToString(first);
   const int slot=sqHandleSlot(key);
   if(slot>=0)
      return g_sq_handle_values[slot];
   return sqRemember(key,iCustom(_Symbol,_Period,name,first));
}

int sqCustomHandle2(const string name,const int first,const int second)
{
   const string key=name+"|"+IntegerToString(first)+"|"+IntegerToString(second);
   const int slot=sqHandleSlot(key);
   if(slot>=0)
      return g_sq_handle_values[slot];
   return sqRemember(key,iCustom(_Symbol,_Period,name,first,second));
}

int sqMaHandle(const ENUM_MA_METHOD method,const ENUM_APPLIED_PRICE source,const int period)
{
   const string key="MA|"+IntegerToString(period)+"|"+IntegerToString((int)method)
                    +"|"+IntegerToString((int)source);
   const int slot=sqHandleSlot(key);
   if(slot>=0)
      return g_sq_handle_values[slot];
   return sqRemember(key,iMA(_Symbol,_Period,period,0,method,source));
}

int sqRsiHandle(const ENUM_APPLIED_PRICE source,const int period)
{
   const string key="RSI|"+IntegerToString(period)+"|"+IntegerToString((int)source);
   const int slot=sqHandleSlot(key);
   if(slot>=0)
      return g_sq_handle_values[slot];
   return sqRemember(key,iRSI(_Symbol,_Period,period,source));
}

int sqStdDevHandle(const ENUM_APPLIED_PRICE source,const int period)
{
   const string key="STDDEV|"+IntegerToString(period)+"|"+IntegerToString((int)source);
   const int slot=sqHandleSlot(key);
   if(slot>=0)
      return g_sq_handle_values[slot];
   return sqRemember(key,iStdDev(_Symbol,_Period,period,0,MODE_SMA,source));
}

double sqPrice(const int field,const int shift)
{
   if(shift<0 || Bars(_Symbol,_Period)<=shift)
      return EMPTY_VALUE;
   if(field==0) return iOpen(_Symbol,_Period,shift);
   if(field==1) return iHigh(_Symbol,_Period,shift);
   if(field==2) return iLow(_Symbol,_Period,shift);
   return iClose(_Symbol,_Period,shift);
}

double sqMa(const ENUM_MA_METHOD method,const ENUM_APPLIED_PRICE source,
            const int period,const int shift)
{
   return sqBufferValue(sqMaHandle(method,source,period),shift);
}

double sqRsi(const ENUM_APPLIED_PRICE source,const int period,const int shift)
{
   return sqBufferValue(sqRsiHandle(source,period),shift);
}

double sqSqAtr(const int period,const int shift)
{
   return sqBufferValue(sqCustomHandle("SqATR",period),shift);
}

double sqSqAdx(const int period,const int shift)
{
   return sqBufferValue(sqCustomHandle("SqADX",period),shift);
}

double sqDirectionalIndex(const int period,const int shift,const int buffer)
{
   const int handle=sqCustomHandle("SqADX",period);
   double values[1];
   if(handle==INVALID_HANDLE || shift<0 || CopyBuffer(handle,buffer,shift,1,values)!=1)
      return EMPTY_VALUE;
   return values[0];
}

double sqPlusDi(const int period,const int shift)
{
   return sqDirectionalIndex(period,shift,1);
}

double sqMinusDi(const int period,const int shift)
{
   return sqDirectionalIndex(period,shift,2);
}

double sqSqRoc(const int period,const int shift)
{
   return sqBufferValue(sqCustomHandle("SqROC",period),shift);
}

double sqExtreme(const ENUM_SERIESMODE mode,const int field,const int period,const int shift,
                 const bool maximum)
{
   // `field` is the QuantForge QFPrice code (0=open,1=high,2=low,3=close).
   // SqHighest/SqLowest expect ENUM_APPLIED_PRICE (PRICE_CLOSE=1, PRICE_HIGH=3, …).
   int price=PRICE_CLOSE;
   if(field==0) price=PRICE_OPEN;
   else if(field==1) price=PRICE_HIGH;
   else if(field==2) price=PRICE_LOW;
   const string indicator=maximum ? "SqHighest" : "SqLowest";
   return sqBufferValue(sqCustomHandle2(indicator,period,price),shift);
}

double sqStdDev(const ENUM_APPLIED_PRICE source,const int period,const int shift)
{
   return sqBufferValue(sqStdDevHandle(source,period),shift);
}

double sqSwingBaseZoneExtreme(const int swing_left,const int swing_right,const int base_bars,
                              const int shift,const bool zone_high)
{
   if(swing_left<1 || swing_right<1 || base_bars<1)
      return EMPTY_VALUE;
   const int total=Bars(_Symbol,_Period);
   const int ready_delay=(swing_right>base_bars ? swing_right : base_bars);
   if(total<=shift+ready_delay+swing_left)
      return EMPTY_VALUE;
   const int target_ri=total-1-shift;
   double last_zone=EMPTY_VALUE;
   for(int ri=0;ri<=target_ri;ri++)
   {
      if(ri<ready_delay)
         continue;
      const int pivot_ri=ri-ready_delay;
      if(pivot_ri<swing_left)
         continue;
      const int pivot_shift=total-1-pivot_ri;
      bool is_swing_low=true;
      bool is_swing_high=true;
      for(int offset=1;offset<=swing_left;offset++)
      {
         if(iLow(_Symbol,_Period,pivot_shift)>iLow(_Symbol,_Period,pivot_shift+offset))
            is_swing_low=false;
         if(iHigh(_Symbol,_Period,pivot_shift)<iHigh(_Symbol,_Period,pivot_shift+offset))
            is_swing_high=false;
      }
      for(int offset=1;offset<=swing_right;offset++)
      {
         if(iLow(_Symbol,_Period,pivot_shift)>=iLow(_Symbol,_Period,pivot_shift-offset))
            is_swing_low=false;
         if(iHigh(_Symbol,_Period,pivot_shift)<=iHigh(_Symbol,_Period,pivot_shift-offset))
            is_swing_high=false;
      }
      const bool use_pivot=zone_high ? is_swing_low : is_swing_high;
      if(!use_pivot)
         continue;
      const int base_start_ri=pivot_ri+1;
      const int base_end_ri=base_start_ri+base_bars-1;
      if(base_end_ri>ri)
         continue;
      double extreme=zone_high ? -DBL_MAX : DBL_MAX;
      for(int bi=base_start_ri;bi<=base_end_ri;bi++)
      {
         const int bar_shift=total-1-bi;
         if(zone_high)
            extreme=MathMax(extreme,iHigh(_Symbol,_Period,bar_shift));
         else
            extreme=MathMin(extreme,iLow(_Symbol,_Period,bar_shift));
      }
      last_zone=extreme;
   }
   return last_zone;
}

double sqSwingBaseZoneHigh(const int swing_left,const int swing_right,const int base_bars,
                           const int shift)
{
   return sqSwingBaseZoneExtreme(swing_left,swing_right,base_bars,shift,true);
}

double sqSwingBaseZoneLow(const int swing_left,const int swing_right,const int base_bars,
                          const int shift)
{
   return sqSwingBaseZoneExtreme(swing_left,swing_right,base_bars,shift,false);
}

double sqSqZScore(const int period,const int shift)
{
   return sqBufferValue(sqCustomHandle("SqZScore",period),shift);
}

double sqSqAtrPercentile(const int atr_period,const int lookback,const int shift)
{
   return sqBufferValue(sqCustomHandle2("SqATRPercentile",atr_period,lookback),shift);
}

double sqLiquiditySweepScore(const int period,const int shift)
{
   const int handle=sqCustomHandle("SqLiquiditySweep",period);
   if(handle==INVALID_HANDLE || shift<0)
      return 0.0;
   double bull[1];
   double bear[1];
   if(CopyBuffer(handle,0,shift,1,bull)!=1 || CopyBuffer(handle,1,shift,1,bear)!=1)
      return 0.0;
   if(bull[0]>0.0)
      return 1.0;
   if(bear[0]>0.0)
      return -1.0;
   return 0.0;
}


#define QFValid sqValid
#define QFPrice sqPrice
#define QFMA sqMa
#define QFRSI sqRsi
#define QFATR sqSqAtr
#define QFADX sqSqAdx
#define QFPlusDI sqPlusDi
#define QFMinusDI sqMinusDi
#define QFStdDev sqStdDev
#define QFExtreme sqExtreme
#define QFSwingBaseZoneHigh sqSwingBaseZoneHigh
#define QFSwingBaseZoneLow sqSwingBaseZoneLow
#define QFLiquiditySweepScore sqLiquiditySweepScore
#define QFGreater sqGreater
#define QFLess sqLess
#define QFCrossAbove sqCrossAbove
#define QFCrossBelow sqCrossBelow

input string CustomComment="QFStopLimitGolden";
input bool   InpAllowLiveTrading=false;
input ulong  InpMagic=42424242;
input int    InpDeviationPoints=10;
input double InpMaxSpreadPoints=0.000000000000;
input double InpEstimatedSlippagePointsPerSide=0.000000000000;
input double InpCommissionPerLotRoundTurn=7.000000000000;
input int    InpEntryWindowStartHour=2;
input int    InpEntryWindowEndHour=19;
input string InpParityPrefix="QuantForge\\QF_c1caf5c06cbc";

CTrade g_trade;
datetime g_last_bar=0;
datetime g_last_exit_bar=0;
int g_loss_streak=0;
int g_decision_bars_seen=0;
int g_entry_day_key=0;
int g_entries_today=0;
int g_deals_file=INVALID_HANDLE;
int g_equity_file=INVALID_HANDLE;
int g_metadata_file=INVALID_HANDLE;
bool g_equity_recorded=false;
double g_last_equity_balance=0.0;
double g_last_equity=0.0;
double g_initial_volume=0.0;
double g_initial_risk=0.0;
double g_peak_favorable=EMPTY_VALUE;
bool g_partial_done[];
bool LongEntrySignal=false;
bool ShortEntrySignal=false;
bool LongExitSignal=false;
bool ShortExitSignal=false;

// Broker specification hash: 81ad02fe3832336e21a39b89a4633dc7c9604d84cf0ecaa299760f875177a296

double QFZScore(const int field,const ENUM_APPLIED_PRICE source,
                const int period,const int shift)
{
   if(field==3 && source==PRICE_CLOSE)
      return sqSqZScore(period,shift);
   const double value=QFPrice(field,shift);
   const double mean=QFMA(MODE_SMA,source,period,shift);
   const double deviation=QFStdDev(source,period,shift);
   if(!QFValid(value) || !QFValid(mean) || !QFValid(deviation) || deviation<=0.0)
      return EMPTY_VALUE;
   return (value-mean)/deviation;
}

double QFPercentile(const int field,const ENUM_SERIESMODE mode,
                    const int period,const int shift)
{
   const double value=QFPrice(field,shift);
   const double low=QFExtreme(mode,field,period,shift,false);
   const double high=QFExtreme(mode,field,period,shift,true);
   if(!QFValid(value) || !QFValid(low) || !QFValid(high) || high<=low)
      return EMPTY_VALUE;
   return (value-low)/(high-low)*100.0;
}

double QFROC(const int field,const int period,const int shift)
{
   if(field==3)
      return sqSqRoc(period,shift);
   const double current=QFPrice(field,shift);
   const double previous=QFPrice(field,shift+period);
   if(!QFValid(current) || !QFValid(previous) || previous==0.0)
      return EMPTY_VALUE;
   return (current/previous-1.0)*100.0;
}

double QFBodyRangeRatio(const int shift)
{
   const double open=QFPrice(0,shift);
   const double high=QFPrice(1,shift);
   const double low=QFPrice(2,shift);
   const double close=QFPrice(3,shift);
   if(!QFValid(open) || !QFValid(high) || !QFValid(low) || !QFValid(close))
      return EMPTY_VALUE;
   const double range=high-low;
   if(range<=0.0)
      return EMPTY_VALUE;
   return MathAbs(close-open)/range;
}

double QFCloseLocationInBar(const int shift)
{
   const double high=QFPrice(1,shift);
   const double low=QFPrice(2,shift);
   const double close=QFPrice(3,shift);
   if(!QFValid(high) || !QFValid(low) || !QFValid(close))
      return EMPTY_VALUE;
   const double range=high-low;
   if(range<=0.0)
      return EMPTY_VALUE;
   return (close-low)/range;
}

double QFAtrPercentile(const int atr_period,const int lookback,const int shift)
{
   if(atr_period<1 || lookback<1 || Bars(_Symbol,_Period)<shift+lookback)
      return EMPTY_VALUE;
   return sqSqAtrPercentile(atr_period,lookback,shift);
}

bool QFSameBrokerDay(const datetime left,const datetime right)
{
   MqlDateTime a,b;
   if(!TimeToStruct(left,a) || !TimeToStruct(right,b))
      return false;
   return a.year==b.year && a.mon==b.mon && a.day==b.day;
}

double QFSessionRangeExtreme(const int start_hour,const int range_bars,const int shift,
                             const bool want_high)
{
   // Mirror quantforge_sqx::session_range_series:
   // 1) first same-day bar with hour >= start_hour is the window start
   // 2) freeze high/low over the next `range_bars` bars (inclusive)
   // 3) carry that frozen extreme for the rest of the day
   if(range_bars<1 || shift<0 || Bars(_Symbol,_Period)<=shift)
      return EMPTY_VALUE;
   const datetime anchor=iTime(_Symbol,_Period,shift);
   if(anchor<=0)
      return EMPTY_VALUE;
   MqlDateTime parts;
   if(!TimeToStruct(anchor,parts))
      return EMPTY_VALUE;

   // Walk oldest→newest on the anchor's broker day to find window start.
   int window_start=-1;
   for(int index=Bars(_Symbol,_Period)-1;index>=shift;index--)
   {
      const datetime bar_time=iTime(_Symbol,_Period,index);
      if(bar_time<=0 || !QFSameBrokerDay(bar_time,anchor))
         continue;
      MqlDateTime bar_parts;
      if(!TimeToStruct(bar_time,bar_parts))
         continue;
      if(bar_parts.hour>=start_hour)
      {
         window_start=index;
         break;
      }
   }
   if(window_start<0)
      return EMPTY_VALUE;

   // Window newest bar index = window_start - (range_bars - 1). Must have formed
   // by `shift` (equal or older than the evaluation bar).
   const int window_end=window_start-(range_bars-1);
   if(window_end<shift)
      return EMPTY_VALUE;

   double extreme=want_high ? -DBL_MAX : DBL_MAX;
   int collected=0;
   for(int index=window_start;index>=window_end;index--)
   {
      const datetime bar_time=iTime(_Symbol,_Period,index);
      if(bar_time<=0 || !QFSameBrokerDay(bar_time,anchor))
         return EMPTY_VALUE;
      MqlDateTime bar_parts;
      if(!TimeToStruct(bar_time,bar_parts) || bar_parts.hour<start_hour)
         return EMPTY_VALUE;
      if(want_high)
         extreme=MathMax(extreme,iHigh(_Symbol,_Period,index));
      else
         extreme=MathMin(extreme,iLow(_Symbol,_Period,index));
      collected++;
   }
   if(collected!=range_bars)
      return EMPTY_VALUE;
   return extreme;
}

double QFSessionRangeHigh(const int start_hour,const int range_bars,const int shift)
{
   return QFSessionRangeExtreme(start_hour,range_bars,shift,true);
}

double QFSessionRangeLow(const int start_hour,const int range_bars,const int shift)
{
   return QFSessionRangeExtreme(start_hour,range_bars,shift,false);
}

double QFAverageRange(const int period,const int shift)
{
   if(period<1 || Bars(_Symbol,_Period)<shift+period)
      return EMPTY_VALUE;
   double sum=0.0;
   for(int index=shift;index<shift+period;index++)
      sum+=iHigh(_Symbol,_Period,index)-iLow(_Symbol,_Period,index);
   return sum/(double)period;
}

double QFContext(const int field,const int shift)
{
   const datetime value=iTime(_Symbol,_Period,shift);
   if(value<=0)
      return EMPTY_VALUE;
   MqlDateTime parts;
   if(!TimeToStruct(value,parts))
      return EMPTY_VALUE;
   return field==0 ? (double)parts.hour : (double)parts.day_of_week;
}

//+------------------------------------------------------------------+
//| QuantForge extended indicators                                    |
//|                                                                   |
//| Shared by both export styles and injected by the generator.        |
//| Each function mirrors the matching arm of                          |
//| quantforge_eval::features::calculate_indicator_series_with_clock.  |
//| Fractional parameters arrive as tenths so the IR stays integral.   |
//+------------------------------------------------------------------+

double QFXBuffer(const int handle,const int buffer,const int shift)
{
   if(handle==INVALID_HANDLE || shift<0)
      return EMPTY_VALUE;
   double values[];
   const int copied=CopyBuffer(handle,buffer,shift,1,values);
   if(copied<1)
      return EMPTY_VALUE;
   return values[0];
}

// Handles live for the whole run. Recreating one per condition atom makes MT5
// rebuild the indicator's history on every tick, which is the single largest
// cost in a generated expert. This cache is deliberately independent of the SQX
// runtime's own cache because both files are inlined into one source.
#define QFX_MAX_HANDLES 32

string g_qfx_handle_keys[QFX_MAX_HANDLES];
int    g_qfx_handle_values[QFX_MAX_HANDLES];
int    g_qfx_handle_count=0;

int QFXCachedHandle(const string key)
{
   for(int index=0;index<g_qfx_handle_count;index++)
      if(g_qfx_handle_keys[index]==key)
         return g_qfx_handle_values[index];
   return -2;
}

int QFXRemember(const string key,const int handle)
{
   if(g_qfx_handle_count<QFX_MAX_HANDLES)
   {
      g_qfx_handle_keys[g_qfx_handle_count]=key;
      g_qfx_handle_values[g_qfx_handle_count]=handle;
      g_qfx_handle_count++;
   }
   return handle;
}

void QFXReleaseHandles()
{
   for(int index=0;index<g_qfx_handle_count;index++)
      if(g_qfx_handle_values[index]!=INVALID_HANDLE)
         IndicatorRelease(g_qfx_handle_values[index]);
   g_qfx_handle_count=0;
}

int QFXMacdHandle(const ENUM_APPLIED_PRICE source,const int fast_period,
                  const int slow_period,const int signal_period)
{
   const string key="MACD|"+IntegerToString(fast_period)+"|"+IntegerToString(slow_period)
                    +"|"+IntegerToString(signal_period)+"|"+IntegerToString((int)source);
   const int cached=QFXCachedHandle(key);
   if(cached!=-2)
      return cached;
   return QFXRemember(key,iMACD(_Symbol,_Period,fast_period,slow_period,signal_period,source));
}

int QFXBandsHandle(const ENUM_APPLIED_PRICE source,const int period,const double deviation)
{
   const string key="BANDS|"+IntegerToString(period)+"|"+DoubleToString(deviation,4)
                    +"|"+IntegerToString((int)source);
   const int cached=QFXCachedHandle(key);
   if(cached!=-2)
      return cached;
   return QFXRemember(key,iBands(_Symbol,_Period,period,0,deviation,source));
}

int QFXIchimokuHandle(const int tenkan,const int kijun,const int senkou)
{
   const string key="ICHIMOKU|"+IntegerToString(tenkan)+"|"+IntegerToString(kijun)
                    +"|"+IntegerToString(senkou);
   const int cached=QFXCachedHandle(key);
   if(cached!=-2)
      return cached;
   return QFXRemember(key,iIchimoku(_Symbol,_Period,tenkan,kijun,senkou));
}

int QFXCciHandle(const int period)
{
   const string key="CCI|"+IntegerToString(period);
   const int cached=QFXCachedHandle(key);
   if(cached!=-2)
      return cached;
   return QFXRemember(key,iCCI(_Symbol,_Period,period,PRICE_TYPICAL));
}

int QFXRsiHandle(const int period)
{
   const string key="QFXRSI|"+IntegerToString(period);
   const int cached=QFXCachedHandle(key);
   if(cached!=-2)
      return cached;
   return QFXRemember(key,iRSI(_Symbol,_Period,period,PRICE_CLOSE));
}

//--- MACD -----------------------------------------------------------
// iMACD MAIN is EMA(fast) - EMA(slow) and SIGNAL is its EMA, which is the
// same construction the Rust evaluator uses.
double QFMacdMain(const ENUM_APPLIED_PRICE source,const int fast_period,
                  const int slow_period,const int signal_period,const int shift)
{
   return QFXBuffer(QFXMacdHandle(source,fast_period,slow_period,signal_period),
                    MAIN_LINE,shift);
}

double QFMacdSignal(const ENUM_APPLIED_PRICE source,const int fast_period,
                    const int slow_period,const int signal_period,const int shift)
{
   return QFXBuffer(QFXMacdHandle(source,fast_period,slow_period,signal_period),
                    SIGNAL_LINE,shift);
}

double QFMacdHistogram(const ENUM_APPLIED_PRICE source,const int fast_period,
                       const int slow_period,const int signal_period,const int shift)
{
   const int handle=QFXMacdHandle(source,fast_period,slow_period,signal_period);
   if(handle==INVALID_HANDLE || shift<0)
      return EMPTY_VALUE;
   double main_values[],signal_values[];
   const int main_copied=CopyBuffer(handle,MAIN_LINE,shift,1,main_values);
   const int signal_copied=CopyBuffer(handle,SIGNAL_LINE,shift,1,signal_values);
   if(main_copied<1 || signal_copied<1)
      return EMPTY_VALUE;
   if(!QFValid(main_values[0]) || !QFValid(signal_values[0]))
      return EMPTY_VALUE;
   return main_values[0]-signal_values[0];
}

//--- Bollinger ------------------------------------------------------
double QFBollinger(const ENUM_APPLIED_PRICE source,const int period,
                   const int deviation_tenths,const int buffer,const int shift)
{
   const double deviation=(double)deviation_tenths/10.0;
   return QFXBuffer(QFXBandsHandle(source,period,deviation),buffer,shift);
}

double QFBollingerMid(const ENUM_APPLIED_PRICE source,const int period,const int shift)
{
   return QFBollinger(source,period,20,BASE_LINE,shift);
}

double QFBollingerUpper(const ENUM_APPLIED_PRICE source,const int period,
                        const int deviation_tenths,const int shift)
{
   return QFBollinger(source,period,deviation_tenths,UPPER_BAND,shift);
}

double QFBollingerLower(const ENUM_APPLIED_PRICE source,const int period,
                        const int deviation_tenths,const int shift)
{
   return QFBollinger(source,period,deviation_tenths,LOWER_BAND,shift);
}

double QFBollingerBandwidth(const ENUM_APPLIED_PRICE source,const int period,
                            const int deviation_tenths,const int shift)
{
   const double deviation=(double)deviation_tenths/10.0;
   const int handle=QFXBandsHandle(source,period,deviation);
   if(handle==INVALID_HANDLE || shift<0)
      return EMPTY_VALUE;
   double base[],upper[],lower[];
   const int base_copied=CopyBuffer(handle,BASE_LINE,shift,1,base);
   const int upper_copied=CopyBuffer(handle,UPPER_BAND,shift,1,upper);
   const int lower_copied=CopyBuffer(handle,LOWER_BAND,shift,1,lower);
   if(base_copied<1 || upper_copied<1 || lower_copied<1)
      return EMPTY_VALUE;
   if(!QFValid(base[0]) || !QFValid(upper[0]) || !QFValid(lower[0]) || base[0]==0.0)
      return EMPTY_VALUE;
   return (upper[0]-lower[0])/base[0]*100.0;
}

//--- Ichimoku -------------------------------------------------------
// Tenkan and Kijun are read in place. The Senkou spans are plotted
// kijun bars ahead of the data that formed them, so the value visible on a
// bar comes from buffer index shift+kijun.
double QFIchimokuTenkan(const int period,const int shift)
{
   return QFXBuffer(QFXIchimokuHandle(period,26,52),TENKANSEN_LINE,shift);
}

double QFIchimokuKijun(const int period,const int shift)
{
   return QFXBuffer(QFXIchimokuHandle(9,period,52),KIJUNSEN_LINE,shift);
}

double QFIchimokuSenkouA(const int tenkan_period,const int kijun_period,const int shift)
{
   return QFXBuffer(QFXIchimokuHandle(tenkan_period,kijun_period,52),
                    SENKOUSPANA_LINE,shift+kijun_period);
}

double QFIchimokuSenkouB(const int period,const int kijun_period,const int shift)
{
   return QFXBuffer(QFXIchimokuHandle(9,kijun_period,period),
                    SENKOUSPANB_LINE,shift+kijun_period);
}

//--- CCI ------------------------------------------------------------
double QFCci(const int period,const int shift)
{
   return QFXBuffer(QFXCciHandle(period),0,shift);
}

//--- VWAP -----------------------------------------------------------
// Rolling volume-weighted typical price. Feeds without tick volume fall back
// to equal weights so the buffer stays defined.
double QFVwap(const int period,const int shift)
{
   if(period<1 || shift<0 || Bars(_Symbol,_Period)<shift+period)
      return EMPTY_VALUE;
   double weighted=0.0;
   double total=0.0;
   for(int index=shift;index<shift+period;index++)
     {
      const double typical=(iHigh(_Symbol,_Period,index)
                            +iLow(_Symbol,_Period,index)
                            +iClose(_Symbol,_Period,index))/3.0;
      double weight=(double)iVolume(_Symbol,_Period,index);
      if(weight<=0.0)
         weight=1.0;
      weighted+=typical*weight;
      total+=weight;
     }
   if(total<=0.0)
      return EMPTY_VALUE;
   return weighted/total;
}

//--- QQE ------------------------------------------------------------
// QQE needs recursive averages over the whole RSI history, so the series is
// built once per bar from a single bulk CopyBuffer and cached. Reading it the
// way the other helpers do (one handle per value) would be orders of magnitude
// slower inside the tester.
#define QF_QQE_MAX_BARS 4096

double   _qf_qqe_line[];
double   _qf_qqe_trail[];
int      _qf_qqe_count=0;
int      _qf_qqe_rsi_period=-1;
int      _qf_qqe_smoothing=-1;
int      _qf_qqe_factor_tenths=-1;
datetime _qf_qqe_stamp=0;

void QFXEmaSparse(const double &values[],const int count,const int period,double &output[])
{
   ArrayResize(output,count);
   for(int index=0;index<count;index++)
      output[index]=EMPTY_VALUE;
   if(period<1 || count<=0)
      return;
   int first=-1;
   for(int index=0;index<count;index++)
      if(QFValid(values[index]))
        {
         first=index;
         break;
        }
   if(first<0 || first+period>count)
      return;
   double sum=0.0;
   for(int index=first;index<first+period;index++)
      sum+=values[index];
   double previous=sum/(double)period;
   output[first+period-1]=previous;
   const double alpha=2.0/((double)period+1.0);
   for(int index=first+period;index<count;index++)
     {
      if(!QFValid(values[index]))
         continue;
      previous=alpha*values[index]+(1.0-alpha)*previous;
      output[index]=previous;
     }
}

// factor_tenths of -1 means the caller only needs the smoothed line, which does
// not depend on the factor; any cached factor is then acceptable.
void QFXQqeBuild(const int rsi_period,const int smoothing_period,const int factor_tenths)
{
   const datetime stamp=iTime(_Symbol,_Period,0);
   const bool same_shape=_qf_qqe_rsi_period==rsi_period
                         && _qf_qqe_smoothing==smoothing_period
                         && _qf_qqe_stamp==stamp
                         && _qf_qqe_count>0;
   if(same_shape && (factor_tenths<0 || _qf_qqe_factor_tenths==factor_tenths))
      return;

   const int effective_factor=factor_tenths<0
                              ? (_qf_qqe_factor_tenths>0 ? _qf_qqe_factor_tenths : 42)
                              : factor_tenths;

   _qf_qqe_rsi_period=rsi_period;
   _qf_qqe_smoothing=smoothing_period;
   _qf_qqe_factor_tenths=effective_factor;
   _qf_qqe_stamp=stamp;
   _qf_qqe_count=0;

   const int available=Bars(_Symbol,_Period);
   int count=available<QF_QQE_MAX_BARS ? available : QF_QQE_MAX_BARS;
   if(count<=rsi_period+smoothing_period+2)
      return;

   const int handle=QFXRsiHandle(rsi_period);
   if(handle==INVALID_HANDLE)
      return;
   double rsi[];
   // Oldest-first ordering so the recursion runs the same direction as Rust.
   const int copied=CopyBuffer(handle,0,0,count,rsi);
   if(copied<1)
      return;
   count=copied;

   double smoothed[];
   QFXEmaSparse(rsi,count,smoothing_period,smoothed);

   double absolute[];
   ArrayResize(absolute,count);
   for(int index=0;index<count;index++)
      absolute[index]=EMPTY_VALUE;
   for(int index=1;index<count;index++)
      if(QFValid(smoothed[index]) && QFValid(smoothed[index-1]))
         absolute[index]=MathAbs(smoothed[index-1]-smoothed[index]);

   int wilder=rsi_period*2-1;
   if(wilder<1)
      wilder=1;
   double smoothed_absolute[];
   QFXEmaSparse(absolute,count,wilder,smoothed_absolute);
   double deviation[];
   QFXEmaSparse(smoothed_absolute,count,wilder,deviation);

   ArrayResize(_qf_qqe_line,count);
   ArrayResize(_qf_qqe_trail,count);
   for(int index=0;index<count;index++)
     {
      _qf_qqe_line[index]=smoothed[index];
      _qf_qqe_trail[index]=EMPTY_VALUE;
     }

   const double factor=(double)effective_factor/10.0;
   double long_band=EMPTY_VALUE;
   double short_band=EMPTY_VALUE;
   bool trend_up=true;
   for(int index=1;index<count;index++)
     {
      if(!QFValid(smoothed[index]) || !QFValid(smoothed[index-1]) || !QFValid(deviation[index]))
         continue;
      const double current=smoothed[index];
      const double previous=smoothed[index-1];
      const double room=deviation[index]*factor;
      const double new_long=current-room;
      const double new_short=current+room;

      if(QFValid(long_band) && previous>long_band && current>long_band)
         long_band=MathMax(long_band,new_long);
      else
         long_band=new_long;

      if(QFValid(short_band) && previous<short_band && current<short_band)
         short_band=MathMin(short_band,new_short);
      else
         short_band=new_short;

      if(current>short_band)
         trend_up=true;
      else
         if(current<long_band)
            trend_up=false;

      _qf_qqe_trail[index]=trend_up ? long_band : short_band;
     }
   _qf_qqe_count=count;
}

double QFQqeLine(const int rsi_period,const int smoothing_period,const int shift)
{
   QFXQqeBuild(rsi_period,smoothing_period,-1);
   if(_qf_qqe_count<=0 || shift<0 || shift>=_qf_qqe_count)
      return EMPTY_VALUE;
   // CopyBuffer returned oldest-first; convert the series shift to that index.
   return _qf_qqe_line[_qf_qqe_count-1-shift];
}

double QFQqeTrail(const int rsi_period,const int smoothing_period,
                  const int factor_tenths,const int shift)
{
   QFXQqeBuild(rsi_period,smoothing_period,factor_tenths);
   if(_qf_qqe_count<=0 || shift<0 || shift>=_qf_qqe_count)
      return EMPTY_VALUE;
   return _qf_qqe_trail[_qf_qqe_count-1-shift];
}


bool QFBetween(const double value,const double lower,const double upper)
{
   return QFValid(value) && QFValid(lower) && QFValid(upper)
          && value>=lower && value<=upper;
}

bool QFLongSignal(const int extra_shift)
{
   return QFCrossAbove(QFMA(MODE_EMA,PRICE_CLOSE,12,(1+extra_shift)),QFMA(MODE_EMA,PRICE_CLOSE,48,(1+extra_shift)),QFMA(MODE_EMA,PRICE_CLOSE,12,(1+(extra_shift+1))),QFMA(MODE_EMA,PRICE_CLOSE,48,(1+(extra_shift+1))));
}

bool QFShortSignal(const int extra_shift)
{
   return false;
}

bool QFExitSignal(const int extra_shift)
{
   if(!QFOwnPosition())
      return false;
   const long position_type = PositionGetInteger(POSITION_TYPE);
   if(position_type == POSITION_TYPE_BUY)
      return false;
   if(position_type == POSITION_TYPE_SELL)
      return false;
   return false;
}

bool QFFilters(const int extra_shift)
{
   return true;
}

double QFStopDistance()
{
   return QFATR(14,1)*2.000000000000;
}

double QFTargetDistance(const double stop_distance)
{
   return stop_distance*3.000000000000;
}

double QFRiskBudget()
{
   return AccountInfoDouble(ACCOUNT_BALANCE)*0.500000000000/100.0;
}

int QFVolumeMode()
{
   return 0;
}

double QFFixedLots()
{
   return 0.0;
}

double QFMartingaleMultiplier()
{
   return 2.0;
}

int QFMartingaleMaxSteps()
{
   return 5;
}

double QFMartingaleLots()
{
   const int steps=(int)MathMin(g_loss_streak,QFMartingaleMaxSteps());
   return QFFixedLots()*MathPow(QFMartingaleMultiplier(),steps);
}


int QFAtrRiskPeriod()
{
   return 14;
}

double QFAtrRiskMultiplier()
{
   return 1.0;
}

double QFAtrRiskMaxLots()
{
   return 0.0;
}

double QFAtrRiskDistance()
{
   const double atr=QFATR(QFAtrRiskPeriod(),1);
   if(!QFValid(atr) || atr<=0.0)
      return 0.0;
   return atr*QFAtrRiskMultiplier();
}
double QFResolveVolume(const double risk_per_lot)
{
   const int mode=QFVolumeMode();
   if(mode==1)
      return QFFixedLots();
   if(mode==2)
      return QFMartingaleLots();
   if(mode==3)
   {
      const double atr_distance=QFAtrRiskDistance();
      if(atr_distance<=0.0)
         return 0.0;
      const double tick_size=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
      const double tick_value=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
      if(tick_size<=0.0 || tick_value<=0.0)
         return 0.0;
      const double atr_risk_per_lot=atr_distance/tick_size*tick_value;
      if(atr_risk_per_lot<=0.0)
         return 0.0;
      double lots=QFRiskBudget()/atr_risk_per_lot;
      const double max_lots=QFAtrRiskMaxLots();
      if(max_lots>0.0)
         lots=MathMin(lots,max_lots);
      return lots;
   }
   if(risk_per_lot<=0.0)
      return 0.0;
   return QFRiskBudget()/risk_per_lot;
}

int QFEntryOrderKind()
{
   return 3;
}

double QFEntryDistance()
{
   return QFATR(14,1)*0.500000000000;
}

double QFEntryLimitOffset()
{
   return QFATR(14,1)*0.250000000000;
}

int QFEntryExpiryBars()
{
   return 4;
}

double QFBreakEvenAtR()
{
   return 0.000000000000;
}

int QFTrailingKind()
{
   return 0;
}

double QFTrailingActivateR()
{
   return 0.000000000000;
}

double QFTrailingDistance()
{
   return 0.0;
}

bool QFFlattenEndOfDay()
{
   return false;
}

bool QFMaxOneEntryPerDay()
{
   return false;
}

int QFMaxTradesPerDay()
{
   return 0;
}

bool QFDontTradeOnWeekends()
{
   return false;
}

bool QFExitOnFriday()
{
   return false;
}

int QFBrokerDayKey(const datetime bar_time)
{
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.year*10000+current.mon*100+current.day;
}

bool QFInMandatoryEntryWindow(const datetime bar_time)
{
   // QuantForge entry session, start inclusive and end exclusive, in
   // broker/chart local time. Must match the window the backtest was run with.
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.hour>=InpEntryWindowStartHour && current.hour<InpEntryWindowEndHour;
}

void QFSyncEntryDay(const datetime bar_time)
{
   const int day_key=QFBrokerDayKey(bar_time);
   if(day_key!=g_entry_day_key)
   {
      g_entry_day_key=day_key;
      g_entries_today=0;
   }
}

bool QFEntryDayExhausted(const datetime bar_time)
{
   QFSyncEntryDay(bar_time);
   int cap=0;
   if(QFMaxOneEntryPerDay())
      cap=1;
   else if(QFMaxTradesPerDay()>0)
      cap=QFMaxTradesPerDay();
   if(cap<=0)
      return false;
   return g_entries_today>=cap;
}

void QFMarkEntrySignalTaken(const datetime bar_time)
{
   QFSyncEntryDay(bar_time);
   g_entries_today++;
}

bool QFWeekendBlocked(const datetime bar_time)
{
   if(!QFDontTradeOnWeekends())
      return false;
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.day_of_week==0 || current.day_of_week==6;
}

bool QFFridayFlattenHour(const datetime bar_time)
{
   if(!QFExitOnFriday())
      return false;
   MqlDateTime current;
   TimeToStruct(bar_time,current);
   return current.day_of_week==5 && current.hour>=23;
}

int QFPartialCount()
{
   return 0;
}

double QFPartialAtR(const int index)
{
   return 0.0;
}

double QFPartialFraction(const int index)
{
   return 0.0;
}

double QFNormalizeVolume(const double requested)
{
   const double minimum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   const double maximum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
   const double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(requested<=0.0 || step<=0.0)
      return 0.0;
   double volume=MathFloor(requested/step+1.0e-12)*step;
   volume=MathMin(volume,maximum);
   if(volume+1.0e-12<minimum)
      return 0.0;
   int digits=0;
   double scaled=step;
   while(digits<8 && MathAbs(scaled-MathRound(scaled))>1.0e-10)
   {
      scaled*=10.0;
      digits++;
   }
   return NormalizeDouble(volume,digits);
}

bool QFApplyPreferredFilling()
{
   ENUM_ORDER_TYPE_FILLING preferred[]={ORDER_FILLING_IOC};
   const int count=1;
   if(count<=0)
      return g_trade.SetTypeFillingBySymbol(_Symbol);
   const long allowed=SymbolInfoInteger(_Symbol,SYMBOL_FILLING_MODE);
   for(int i=0;i<count && i<ArraySize(preferred);i++)
   {
      long flag=0;
      if(preferred[i]==ORDER_FILLING_FOK)
         flag=SYMBOL_FILLING_FOK;
      else if(preferred[i]==ORDER_FILLING_IOC)
         flag=SYMBOL_FILLING_IOC;
      else if(preferred[i]==ORDER_FILLING_RETURN)
         flag=4; // SYMBOL_FILLING_RETURN — named constant missing on some terminal builds
      if(flag!=0 && (allowed&flag)==flag)
      {
         g_trade.SetTypeFilling(preferred[i]);
         return true;
      }
   }
   return g_trade.SetTypeFillingBySymbol(_Symbol);
}

bool QFOpenOrder(const bool buy)
{
   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick))
      return false;
   const double stop_distance=QFStopDistance();
   const double target_distance=QFTargetDistance(stop_distance);
   if(!QFValid(stop_distance) || !QFValid(target_distance)
      || stop_distance<=0.0 || target_distance<=0.0)
      return false;
   const int entry_kind=QFEntryOrderKind();
   const double entry_distance=QFEntryDistance();
   const double limit_offset=QFEntryLimitOffset();
   if(entry_kind!=0 && (!QFValid(entry_distance) || entry_distance<=0.0))
      return false;
   if(entry_kind==3 && (!QFValid(limit_offset) || limit_offset<=0.0))
      return false;
   const double minimum_distance=(double)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL)*_Point;
   if(stop_distance<minimum_distance || target_distance<minimum_distance
      || (entry_kind!=0 && entry_distance<minimum_distance)
      || (entry_kind==3 && limit_offset<minimum_distance))
      return false;

   const double reference=buy ? tick.ask : tick.bid;
   double intended_entry=reference;
   double stop_trigger=0.0;
   if(entry_kind==1)
      intended_entry=buy ? reference+entry_distance : reference-entry_distance;
   else if(entry_kind==2)
      intended_entry=buy ? reference-entry_distance : reference+entry_distance;
   else if(entry_kind==3)
   {
      stop_trigger=buy ? reference+entry_distance : reference-entry_distance;
      intended_entry=buy ? stop_trigger-limit_offset : stop_trigger+limit_offset;
      stop_trigger=NormalizeDouble(stop_trigger,_Digits);
   }
   intended_entry=NormalizeDouble(intended_entry,_Digits);
   const double stop=NormalizeDouble(buy ? intended_entry-stop_distance
                                         : intended_entry+stop_distance,_Digits);
   const double target=NormalizeDouble(buy ? intended_entry+target_distance
                                           : intended_entry-target_distance,_Digits);
   double loss_per_lot=0.0;
   const ENUM_ORDER_TYPE market_type=buy ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
   if(!OrderCalcProfit(market_type,_Symbol,1.0,intended_entry,stop,loss_per_lot))
      return false;
   loss_per_lot=MathAbs(loss_per_lot);
   const double tick_size=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
   const double tick_value=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
   if(tick_size<=0.0 || tick_value<=0.0)
      return false;
   const double slippage_cost=2.0*InpEstimatedSlippagePointsPerSide*_Point/tick_size*tick_value;
   const double risk_per_lot=loss_per_lot+InpCommissionPerLotRoundTurn+slippage_cost;
   if(risk_per_lot<=0.0)
      return false;
   const double volume=QFNormalizeVolume(QFResolveVolume(risk_per_lot));
   if(volume<=0.0)
      return false;

   g_trade.SetExpertMagicNumber(InpMagic);
   g_trade.SetDeviationInPoints(InpDeviationPoints);
   QFApplyPreferredFilling();
   const string comment="QF-c1caf5c06cbc";
   bool sent=false;
   if(entry_kind==0)
      sent=buy
           ? g_trade.Buy(volume,_Symbol,0.0,stop,target,comment)
           : g_trade.Sell(volume,_Symbol,0.0,stop,target,comment);
   else
   {
      const datetime expiration=iTime(_Symbol,_Period,0)
                                +(datetime)(QFEntryExpiryBars()*PeriodSeconds(_Period));
      if(entry_kind==1)
         sent=buy
              ? g_trade.BuyStop(volume,intended_entry,_Symbol,stop,target,
                                ORDER_TIME_SPECIFIED,expiration,comment)
              : g_trade.SellStop(volume,intended_entry,_Symbol,stop,target,
                                 ORDER_TIME_SPECIFIED,expiration,comment);
      else if(entry_kind==2)
         sent=buy
              ? g_trade.BuyLimit(volume,intended_entry,_Symbol,stop,target,
                                 ORDER_TIME_SPECIFIED,expiration,comment)
              : g_trade.SellLimit(volume,intended_entry,_Symbol,stop,target,
                                  ORDER_TIME_SPECIFIED,expiration,comment);
      else
         // Prefer OrderOpen over CTrade::BuyStopLimit — older Trade.mqh builds lack the helpers.
         sent=buy
              ? g_trade.OrderOpen(_Symbol,ORDER_TYPE_BUY_STOP_LIMIT,volume,intended_entry,stop_trigger,stop,target,
                                  ORDER_TIME_SPECIFIED,expiration,comment)
              : g_trade.OrderOpen(_Symbol,ORDER_TYPE_SELL_STOP_LIMIT,volume,intended_entry,stop_trigger,stop,target,
                                  ORDER_TIME_SPECIFIED,expiration,comment);
   }
   if(!sent)
      Print("QuantForge entry rejected: ",g_trade.ResultRetcodeDescription());
   else if(entry_kind==0)
      g_initial_volume=0.0;
   return sent;
}

bool QFOwnPosition()
{
   if(!PositionSelect(_Symbol))
      return false;
   return (ulong)PositionGetInteger(POSITION_MAGIC)==InpMagic;
}

bool QFOwnPendingOrder()
{
   for(int index=OrdersTotal()-1;index>=0;index--)
   {
      const ulong ticket=OrderGetTicket(index);
      if(ticket==0)
         continue;
      if(OrderGetString(ORDER_SYMBOL)==_Symbol
         && (ulong)OrderGetInteger(ORDER_MAGIC)==InpMagic)
         return true;
   }
   return false;
}

void QFCancelOwnOrders()
{
   for(int index=OrdersTotal()-1;index>=0;index--)
   {
      const ulong ticket=OrderGetTicket(index);
      if(ticket==0)
         continue;
      if(OrderGetString(ORDER_SYMBOL)==_Symbol
         && (ulong)OrderGetInteger(ORDER_MAGIC)==InpMagic
         && !g_trade.OrderDelete(ticket))
         Print("QuantForge pending-order cancellation rejected: ",
               g_trade.ResultRetcodeDescription());
   }
}

void QFResetPositionState()
{
   g_initial_volume=0.0;
   g_initial_risk=0.0;
   g_peak_favorable=EMPTY_VALUE;
   ArrayInitialize(g_partial_done,false);
}

// Fill-aware favorable extreme from completed decision bar's M1 path.
// Entry minute: close only. Later minutes: high/low. Ignores pre-entry minutes.
double QFFavorableSampleSinceEntry(const bool buy)
{
   if(!QFOwnPosition())
      return EMPTY_VALUE;
   const datetime entry=(datetime)PositionGetInteger(POSITION_TIME);
   const int entry_shift=iBarShift(_Symbol,PERIOD_M1,entry,false);
   if(entry_shift<0)
      return EMPTY_VALUE;
   const datetime entry_minute=iTime(_Symbol,PERIOD_M1,entry_shift);
   const datetime completed_start=iTime(_Symbol,_Period,1);
   const datetime completed_end=iTime(_Symbol,_Period,0);
   if(completed_start<=0 || completed_end<=completed_start)
      return EMPTY_VALUE;
   MqlRates rates[];
   const int copied=CopyRates(_Symbol,PERIOD_M1,completed_start,completed_end-1,rates);
   if(copied<=0)
      return EMPTY_VALUE;
   const double completed_spread=(double)iSpread(_Symbol,_Period,1)*_Point;
   double best=EMPTY_VALUE;
   for(int index=0;index<copied;index++)
   {
      if(rates[index].time<entry_minute)
         continue;
      double sample;
      if(rates[index].time==entry_minute)
         sample=rates[index].close;
      else
         sample=buy ? rates[index].high : rates[index].low;
      if(!buy)
         sample+=completed_spread;
      if(best==EMPTY_VALUE)
         best=sample;
      else
         best=buy ? MathMax(best,sample) : MathMin(best,sample);
   }
   return best;
}

void QFRatchetPeakFavorable(const bool buy,const double sample)
{
   if(!QFValid(sample))
      return;
   if(g_peak_favorable==EMPTY_VALUE)
      g_peak_favorable=sample;
   else
      g_peak_favorable=buy ? MathMax(g_peak_favorable,sample)
                           : MathMin(g_peak_favorable,sample);
}

void QFCapturePositionState()
{
   if(!QFOwnPosition() || g_initial_volume>0.0)
      return;
   const double entry=PositionGetDouble(POSITION_PRICE_OPEN);
   const double stop=PositionGetDouble(POSITION_SL);
   g_initial_volume=PositionGetDouble(POSITION_VOLUME);
   g_initial_risk=MathAbs(entry-stop);
   ArrayInitialize(g_partial_done,false);
}

double QFNormalizePartialVolume(const double requested,const double remaining)
{
   const double minimum=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   const double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(requested+1.0e-12>=remaining)
      return remaining;
   double volume=MathFloor(requested/step+1.0e-12)*step;
   if(volume+1.0e-12<minimum)
      return 0.0;
   if(remaining-volume+1.0e-12<minimum)
      volume=remaining;
   return QFNormalizeVolume(volume);
}

bool QFClosePartial(const double volume)
{
   if(!QFOwnPosition() || volume<=0.0)
      return false;
   const ENUM_POSITION_TYPE type=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   const long margin_mode=AccountInfoInteger(ACCOUNT_MARGIN_MODE);
   if(margin_mode==ACCOUNT_MARGIN_MODE_RETAIL_HEDGING)
      return g_trade.PositionClosePartial(_Symbol,volume,InpDeviationPoints);
   return type==POSITION_TYPE_BUY
          ? g_trade.Sell(volume,_Symbol,0.0,0.0,0.0,"QF-partial")
          : g_trade.Buy(volume,_Symbol,0.0,0.0,0.0,"QF-partial");
}

bool QFInCloseBlackout()
{
   MqlDateTime current;
   if(!TimeToStruct(iTime(_Symbol,_Period,0),current))
      return false;
   return current.hour>=23;
}

bool QFStopWouldTriggerAtOpen(const bool buy,const double candidate,
                              const double bar_open,const double bar_spread)
{
   if(!QFValid(candidate))
      return true;
   return buy ? (bar_open<=candidate+1.0e-12)
              : (bar_open+bar_spread>=candidate-1.0e-12);
}

// Clamp to stops-level, or EMPTY_VALUE if the stop would already trigger at open
// (matches Rust placeable_stop_candidate / MT5 PositionModify reject).
double QFPlaceableStop(const bool buy,const double raw,const double bar_open,
                       const double bar_spread,const double minimum_distance)
{
   if(!QFValid(raw))
      return EMPTY_VALUE;
   const double candidate=buy ? MathMin(raw,bar_open-minimum_distance)
                              : MathMax(raw,bar_open+bar_spread+minimum_distance);
   if(QFStopWouldTriggerAtOpen(buy,candidate,bar_open,bar_spread))
      return EMPTY_VALUE;
   return candidate;
}

bool QFTightenStop(const bool buy,const double candidate,const double target)
{
   const double current=PositionGetDouble(POSITION_SL);
   if(!QFValid(candidate)
      || (buy && candidate<=current+1.0e-12)
      || (!buy && candidate>=current-1.0e-12))
      return false;
   if(!g_trade.PositionModify(_Symbol,NormalizeDouble(candidate,_Digits),target))
   {
      Print("QuantForge stop modification rejected: ",g_trade.ResultRetcodeDescription());
      return false;
   }
   return true;
}

void QFManagePosition()
{
   if(!QFOwnPosition())
   {
      QFResetPositionState();
      return;
   }
   QFCapturePositionState();
   if(g_initial_volume<=0.0 || g_initial_risk<=0.0)
      return;
   const ENUM_POSITION_TYPE type=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   const bool buy=type==POSITION_TYPE_BUY;
   const double entry=PositionGetDouble(POSITION_PRICE_OPEN);
   const double target=PositionGetDouble(POSITION_TP);
   const double sample=QFFavorableSampleSinceEntry(buy);
   QFRatchetPeakFavorable(buy,sample);
   if(!QFValid(g_peak_favorable))
      return;
   const double favorable=g_peak_favorable;
   const double favorable_r=buy ? (favorable-entry)/g_initial_risk
                                : (entry-favorable)/g_initial_risk;
   const double minimum_distance=
      (double)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL)*_Point;
   // Match Rust: placeable stops only — never clamp a through-market trail onto
   // the open (that invents an immediate runner exit MT5 would reject).
   const double bar_open=iOpen(_Symbol,_Period,0);
   const double bar_spread=(double)iSpread(_Symbol,_Period,0)*_Point;

   if(QFBreakEvenAtR()>0.0 && favorable_r>=QFBreakEvenAtR())
   {
      const double candidate=QFPlaceableStop(buy,entry,bar_open,bar_spread,minimum_distance);
      if(QFValid(candidate))
         QFTightenStop(buy,candidate,target);
   }
   if(QFTrailingKind()>0 && favorable_r>=QFTrailingActivateR())
   {
      const double distance=QFTrailingDistance();
      if(QFValid(distance) && distance>0.0)
      {
         const double raw=buy ? favorable-distance : favorable+distance;
         const double candidate=QFPlaceableStop(buy,raw,bar_open,bar_spread,minimum_distance);
         if(QFValid(candidate))
            QFTightenStop(buy,candidate,target);
      }
   }

   for(int index=0;index<QFPartialCount() && QFOwnPosition();index++)
   {
      if(g_partial_done[index] || favorable_r<QFPartialAtR(index))
         continue;
      const double remaining=PositionGetDouble(POSITION_VOLUME);
      const double volume=QFNormalizePartialVolume(
         g_initial_volume*QFPartialFraction(index),remaining);
      if(volume<=0.0)
         continue;
      if(QFClosePartial(volume))
         g_partial_done[index]=true;
      else
         Print("QuantForge partial exit rejected: ",g_trade.ResultRetcodeDescription());
   }
}

bool QFTimeStopReached()
{
   const int limit=48;
   if(limit<=0 || !QFOwnPosition())
      return false;
   const datetime entry_time=(datetime)PositionGetInteger(POSITION_TIME);
   const int bars_held=iBarShift(_Symbol,_Period,entry_time,false);
   return bars_held>=limit;
}

void QFRecordEquity(const datetime bar_time)
{
   if(g_equity_file==INVALID_HANDLE)
      return;
   const double balance=AccountInfoDouble(ACCOUNT_BALANCE);
   const double equity=AccountInfoDouble(ACCOUNT_EQUITY);
   // A repeated sample can move neither the peak, the drawdown nor the ending
   // balance, so skipping it keeps the parity metrics identical while removing
   // one row per tick from the hot path. OnDeinit still flushes and closes, so
   // per-record flushing only bought crash resilience at a large cost.
   if(g_equity_recorded && balance==g_last_equity_balance && equity==g_last_equity)
      return;
   g_equity_recorded=true;
   g_last_equity_balance=balance;
   g_last_equity=equity;
   FileWrite(g_equity_file,(long)bar_time*1000,balance,equity);
}

int OnInit()
{
   if(_Symbol!="EURNZD")
   {
      Print("QuantForge export is broker-bound to EURNZD, not ",_Symbol);
      return INIT_PARAMETERS_INCORRECT;
   }
   if(!(bool)MQLInfoInteger(MQL_TESTER) && !InpAllowLiveTrading)
   {
      Print("QuantForge live trading is disabled. Explicitly enable InpAllowLiveTrading only after certification.");
      return INIT_FAILED;
   }
   g_trade.SetExpertMagicNumber(InpMagic);
   g_trade.SetDeviationInPoints(InpDeviationPoints);
   QFApplyPreferredFilling();
   ArrayResize(g_partial_done,QFPartialCount());
   QFResetPositionState();
   g_last_bar=iTime(_Symbol,_Period,0);

   if((bool)MQLInfoInteger(MQL_TESTER) && StringLen(InpParityPrefix)>0)
   {
      FolderCreate("QuantForge",FILE_COMMON);
      g_deals_file=FileOpen(InpParityPrefix+"_deals.csv",
                            FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      g_equity_file=FileOpen(InpParityPrefix+"_equity.csv",
                             FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      g_metadata_file=FileOpen(InpParityPrefix+"_metadata.csv",
                               FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',',CP_UTF8);
      if(g_deals_file!=INVALID_HANDLE)
         FileWrite(g_deals_file,"deal_ticket","position_id","timestamp_ms","deal_type",
                   "deal_entry","price","volume","profit","commission","swap","fee");
      if(g_equity_file!=INVALID_HANDLE)
         FileWrite(g_equity_file,"timestamp_ms","balance","equity");
      if(g_metadata_file!=INVALID_HANDLE)
      {
         FileWrite(g_metadata_file,"property","value");
         FileWrite(g_metadata_file,"strategy_fingerprint","c1caf5c06cbc15e55c971b7ed6d172fda5ab65fa5732447e9300333b7609b2f6");
         FileWrite(g_metadata_file,"broker_spec_hash","81ad02fe3832336e21a39b89a4633dc7c9604d84cf0ecaa299760f875177a296");
         FileWrite(g_metadata_file,"terminal_build",TerminalInfoInteger(TERMINAL_BUILD));
         FileWrite(g_metadata_file,"broker",AccountInfoString(ACCOUNT_COMPANY));
         FileWrite(g_metadata_file,"server",AccountInfoString(ACCOUNT_SERVER));
         FileWrite(g_metadata_file,"symbol",_Symbol);
         FileWrite(g_metadata_file,"timeframe",EnumToString(_Period));
         FileWrite(g_metadata_file,"magic",InpMagic);
         FileWrite(g_metadata_file,"deviation_points",InpDeviationPoints);
         FileWrite(g_metadata_file,"max_spread_points",InpMaxSpreadPoints);
         FileWrite(g_metadata_file,"estimated_slippage_points_per_side",
                   InpEstimatedSlippagePointsPerSide);
         FileWrite(g_metadata_file,"commission_per_lot_round_turn",
                   InpCommissionPerLotRoundTurn);
         FileWrite(g_metadata_file,"risk_budget",QFRiskBudget());
         FileWrite(g_metadata_file,"initial_deposit",AccountInfoDouble(ACCOUNT_BALANCE));
         FileWrite(g_metadata_file,"account_currency",AccountInfoString(ACCOUNT_CURRENCY));
         // Same token QuantForge uses for bar localization (must match the pack).
         FileWrite(g_metadata_file,"broker_timezone","ICMarkets/EST+7");
         FileWrite(g_metadata_file,"server_utc_offset_seconds_at_export",
                   (long)(TimeTradeServer()-TimeGMT()));
         FileWrite(g_metadata_file,"started_server_time",TimeToString(TimeCurrent(),TIME_DATE|TIME_SECONDS));
         FileFlush(g_metadata_file);
      }
   }
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   // Match Scout/Judge EndOfData: flatten any live position before the tester
   // tears down so deals.csv always contains exit legs.
   if(MQLInfoInteger(MQL_TESTER) && QFOwnPosition())
   {
      if(!g_trade.PositionClose(_Symbol,InpDeviationPoints))
         Print("QuantForge end-of-data flatten rejected: ",
               g_trade.ResultRetcodeDescription());
   }
   QFCancelOwnOrders();
   sqReleaseHandles();
   QFXReleaseHandles();
   if(g_deals_file!=INVALID_HANDLE)
   {
      FileFlush(g_deals_file);
      FileClose(g_deals_file);
   }
   if(g_equity_file!=INVALID_HANDLE)
   {
      FileFlush(g_equity_file);
      FileClose(g_equity_file);
   }
   if(g_metadata_file!=INVALID_HANDLE)
   {
      FileWrite(g_metadata_file,"finished_server_time",TimeToString(TimeCurrent(),TIME_DATE|TIME_SECONDS));
      FileFlush(g_metadata_file);
      FileClose(g_metadata_file);
   }
}

void OnTradeTransaction(const MqlTradeTransaction &transaction,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result)
{
   if(transaction.type!=TRADE_TRANSACTION_DEAL_ADD || transaction.deal==0
      || !HistoryDealSelect(transaction.deal))
      return;
   if((ulong)HistoryDealGetInteger(transaction.deal,DEAL_MAGIC)!=InpMagic)
      return;
   const ENUM_DEAL_ENTRY deal_entry=
      (ENUM_DEAL_ENTRY)HistoryDealGetInteger(transaction.deal,DEAL_ENTRY);
   if(deal_entry==DEAL_ENTRY_IN)
   {
      g_initial_volume=0.0;
      QFCapturePositionState();
      // First fill locks the broker day (pending place alone does not).
      QFMarkEntrySignalTaken(iTime(_Symbol,_Period,0));
   }
   if(deal_entry==DEAL_ENTRY_OUT || deal_entry==DEAL_ENTRY_OUT_BY)
   {
      const double deal_profit=HistoryDealGetDouble(transaction.deal,DEAL_PROFIT)
         +HistoryDealGetDouble(transaction.deal,DEAL_SWAP)
         +HistoryDealGetDouble(transaction.deal,DEAL_COMMISSION)
         +HistoryDealGetDouble(transaction.deal,DEAL_FEE);
      if(deal_profit<0.0)
         g_loss_streak++;
      else if(deal_profit>0.0)
         g_loss_streak=0;
      g_last_exit_bar=iTime(_Symbol,_Period,0);
      if(!QFOwnPosition())
         QFResetPositionState();
   }
   if(g_deals_file==INVALID_HANDLE)
      return;
   FileWrite(g_deals_file,
             transaction.deal,
             (ulong)HistoryDealGetInteger(transaction.deal,DEAL_POSITION_ID),
             (long)HistoryDealGetInteger(transaction.deal,DEAL_TIME_MSC),
             EnumToString((ENUM_DEAL_TYPE)HistoryDealGetInteger(transaction.deal,DEAL_TYPE)),
             EnumToString(deal_entry),
             HistoryDealGetDouble(transaction.deal,DEAL_PRICE),
             HistoryDealGetDouble(transaction.deal,DEAL_VOLUME),
             HistoryDealGetDouble(transaction.deal,DEAL_PROFIT),
             HistoryDealGetDouble(transaction.deal,DEAL_COMMISSION),
             HistoryDealGetDouble(transaction.deal,DEAL_SWAP),
             HistoryDealGetDouble(transaction.deal,DEAL_FEE));
   FileFlush(g_deals_file);
}

void OnTick()
{
   checkBarOpen();
   const datetime current_bar=iTime(_Symbol,_Period,0);
   if(current_bar<=0)
      return;
   if(_sqIsBarOpen)
      g_decision_bars_seen++;

   if((QFFlattenEndOfDay() && QFInCloseBlackout()) || QFFridayFlattenHour(current_bar))
   {
      QFCancelOwnOrders();
      if(QFOwnPosition()
         && !g_trade.PositionClose(_Symbol,InpDeviationPoints))
         Print("QuantForge end-of-day exit rejected: ",
               g_trade.ResultRetcodeDescription());
      QFRecordEquity(current_bar);
      return;
   }

   // Hard session: cancel unfilled pending outside [02:00, 19:00).
   if(!QFInMandatoryEntryWindow(current_bar))
      QFCancelOwnOrders();

   QFManagePosition();

   if(QFOwnPosition() && (QFExitSignal(0) || QFTimeStopReached()))
   {
      if(!g_trade.PositionClose(_Symbol,InpDeviationPoints))
         Print("QuantForge exit rejected: ",g_trade.ResultRetcodeDescription());
      QFRecordEquity(current_bar);
      return;
   }
   if(PositionSelect(_Symbol) || QFOwnPendingOrder() || !QFFilters(0))
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(g_last_exit_bar==current_bar)
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(QFWeekendBlocked(current_bar))
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(!QFInMandatoryEntryWindow(current_bar))
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(!_sqIsBarOpen)
   {
      QFRecordEquity(current_bar);
      return;
   }
   // MT5 retains pre-test indicator history while QuantForge packs begin at
   // the selected date. Wait for the shared recursive-buffer convergence gate.
   if(g_decision_bars_seen<320)
   {
      QFRecordEquity(current_bar);
      return;
   }
   if(QFEntryDayExhausted(current_bar))
   {
      QFRecordEquity(current_bar);
      return;
   }

   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick))
      return;
   const double spread_points=(tick.ask-tick.bid)/_Point;
   if(InpMaxSpreadPoints>0.0 && spread_points>InpMaxSpreadPoints)
   {
      QFRecordEquity(current_bar);
      return;
   }

   LongEntrySignal=QFLongSignal(0);
   ShortEntrySignal=QFShortSignal(0);
   const bool long_signal=LongEntrySignal;
   const bool short_signal=ShortEntrySignal;
   if(long_signal!=short_signal)
   {
      // Place only; day lock happens on fill (DEAL_ENTRY_IN / market position).
      if(QFOpenOrder(long_signal))
      {
         QFCapturePositionState();
         if(QFOwnPosition())
            QFMarkEntrySignalTaken(current_bar);
      }
   }
   QFRecordEquity(current_bar);
}
